// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: grpc/asr.proto
#ifndef GRPC_grpc_2fasr_2eproto__INCLUDED
#define GRPC_grpc_2fasr_2eproto__INCLUDED

#include "grpc/asr.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>

namespace asr {
namespace v1 {

// Service that implements ASR
class ASR final {
 public:
  static constexpr char const* service_full_name() {
    return "asr.v1.ASR";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    // ASR in one sentence case. It will STOP recognition after the very first endpoint.
    std::unique_ptr< ::grpc::ClientReaderWriterInterface< ::asr::v1::Request, ::asr::v1::Response>> OneSentenceSpeechRecognition(::grpc::ClientContext* context) {
      return std::unique_ptr< ::grpc::ClientReaderWriterInterface< ::asr::v1::Request, ::asr::v1::Response>>(OneSentenceSpeechRecognitionRaw(context));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::asr::v1::Request, ::asr::v1::Response>> AsyncOneSentenceSpeechRecognition(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::asr::v1::Request, ::asr::v1::Response>>(AsyncOneSentenceSpeechRecognitionRaw(context, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::asr::v1::Request, ::asr::v1::Response>> PrepareAsyncOneSentenceSpeechRecognition(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::asr::v1::Request, ::asr::v1::Response>>(PrepareAsyncOneSentenceSpeechRecognitionRaw(context, cq));
    }
    // Real-time streaming recognition. It will CONTINUE recognition after each endpoint.
    std::unique_ptr< ::grpc::ClientReaderWriterInterface< ::asr::v1::Request, ::asr::v1::Response>> RealTimeSpeechRecognition(::grpc::ClientContext* context) {
      return std::unique_ptr< ::grpc::ClientReaderWriterInterface< ::asr::v1::Request, ::asr::v1::Response>>(RealTimeSpeechRecognitionRaw(context));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::asr::v1::Request, ::asr::v1::Response>> AsyncRealTimeSpeechRecognition(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::asr::v1::Request, ::asr::v1::Response>>(AsyncRealTimeSpeechRecognitionRaw(context, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::asr::v1::Request, ::asr::v1::Response>> PrepareAsyncRealTimeSpeechRecognition(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::asr::v1::Request, ::asr::v1::Response>>(PrepareAsyncRealTimeSpeechRecognitionRaw(context, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      // ASR in one sentence case. It will STOP recognition after the very first endpoint.
      virtual void OneSentenceSpeechRecognition(::grpc::ClientContext* context, ::grpc::ClientBidiReactor< ::asr::v1::Request,::asr::v1::Response>* reactor) = 0;
      // Real-time streaming recognition. It will CONTINUE recognition after each endpoint.
      virtual void RealTimeSpeechRecognition(::grpc::ClientContext* context, ::grpc::ClientBidiReactor< ::asr::v1::Request,::asr::v1::Response>* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientReaderWriterInterface< ::asr::v1::Request, ::asr::v1::Response>* OneSentenceSpeechRecognitionRaw(::grpc::ClientContext* context) = 0;
    virtual ::grpc::ClientAsyncReaderWriterInterface< ::asr::v1::Request, ::asr::v1::Response>* AsyncOneSentenceSpeechRecognitionRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) = 0;
    virtual ::grpc::ClientAsyncReaderWriterInterface< ::asr::v1::Request, ::asr::v1::Response>* PrepareAsyncOneSentenceSpeechRecognitionRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientReaderWriterInterface< ::asr::v1::Request, ::asr::v1::Response>* RealTimeSpeechRecognitionRaw(::grpc::ClientContext* context) = 0;
    virtual ::grpc::ClientAsyncReaderWriterInterface< ::asr::v1::Request, ::asr::v1::Response>* AsyncRealTimeSpeechRecognitionRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) = 0;
    virtual ::grpc::ClientAsyncReaderWriterInterface< ::asr::v1::Request, ::asr::v1::Response>* PrepareAsyncRealTimeSpeechRecognitionRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    std::unique_ptr< ::grpc::ClientReaderWriter< ::asr::v1::Request, ::asr::v1::Response>> OneSentenceSpeechRecognition(::grpc::ClientContext* context) {
      return std::unique_ptr< ::grpc::ClientReaderWriter< ::asr::v1::Request, ::asr::v1::Response>>(OneSentenceSpeechRecognitionRaw(context));
    }
    std::unique_ptr<  ::grpc::ClientAsyncReaderWriter< ::asr::v1::Request, ::asr::v1::Response>> AsyncOneSentenceSpeechRecognition(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriter< ::asr::v1::Request, ::asr::v1::Response>>(AsyncOneSentenceSpeechRecognitionRaw(context, cq, tag));
    }
    std::unique_ptr<  ::grpc::ClientAsyncReaderWriter< ::asr::v1::Request, ::asr::v1::Response>> PrepareAsyncOneSentenceSpeechRecognition(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriter< ::asr::v1::Request, ::asr::v1::Response>>(PrepareAsyncOneSentenceSpeechRecognitionRaw(context, cq));
    }
    std::unique_ptr< ::grpc::ClientReaderWriter< ::asr::v1::Request, ::asr::v1::Response>> RealTimeSpeechRecognition(::grpc::ClientContext* context) {
      return std::unique_ptr< ::grpc::ClientReaderWriter< ::asr::v1::Request, ::asr::v1::Response>>(RealTimeSpeechRecognitionRaw(context));
    }
    std::unique_ptr<  ::grpc::ClientAsyncReaderWriter< ::asr::v1::Request, ::asr::v1::Response>> AsyncRealTimeSpeechRecognition(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriter< ::asr::v1::Request, ::asr::v1::Response>>(AsyncRealTimeSpeechRecognitionRaw(context, cq, tag));
    }
    std::unique_ptr<  ::grpc::ClientAsyncReaderWriter< ::asr::v1::Request, ::asr::v1::Response>> PrepareAsyncRealTimeSpeechRecognition(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriter< ::asr::v1::Request, ::asr::v1::Response>>(PrepareAsyncRealTimeSpeechRecognitionRaw(context, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void OneSentenceSpeechRecognition(::grpc::ClientContext* context, ::grpc::ClientBidiReactor< ::asr::v1::Request,::asr::v1::Response>* reactor) override;
      void RealTimeSpeechRecognition(::grpc::ClientContext* context, ::grpc::ClientBidiReactor< ::asr::v1::Request,::asr::v1::Response>* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientReaderWriter< ::asr::v1::Request, ::asr::v1::Response>* OneSentenceSpeechRecognitionRaw(::grpc::ClientContext* context) override;
    ::grpc::ClientAsyncReaderWriter< ::asr::v1::Request, ::asr::v1::Response>* AsyncOneSentenceSpeechRecognitionRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) override;
    ::grpc::ClientAsyncReaderWriter< ::asr::v1::Request, ::asr::v1::Response>* PrepareAsyncOneSentenceSpeechRecognitionRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientReaderWriter< ::asr::v1::Request, ::asr::v1::Response>* RealTimeSpeechRecognitionRaw(::grpc::ClientContext* context) override;
    ::grpc::ClientAsyncReaderWriter< ::asr::v1::Request, ::asr::v1::Response>* AsyncRealTimeSpeechRecognitionRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) override;
    ::grpc::ClientAsyncReaderWriter< ::asr::v1::Request, ::asr::v1::Response>* PrepareAsyncRealTimeSpeechRecognitionRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_OneSentenceSpeechRecognition_;
    const ::grpc::internal::RpcMethod rpcmethod_RealTimeSpeechRecognition_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    // ASR in one sentence case. It will STOP recognition after the very first endpoint.
    virtual ::grpc::Status OneSentenceSpeechRecognition(::grpc::ServerContext* context, ::grpc::ServerReaderWriter< ::asr::v1::Response, ::asr::v1::Request>* stream);
    // Real-time streaming recognition. It will CONTINUE recognition after each endpoint.
    virtual ::grpc::Status RealTimeSpeechRecognition(::grpc::ServerContext* context, ::grpc::ServerReaderWriter< ::asr::v1::Response, ::asr::v1::Request>* stream);
  };
  template <class BaseClass>
  class WithAsyncMethod_OneSentenceSpeechRecognition : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_OneSentenceSpeechRecognition() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_OneSentenceSpeechRecognition() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status OneSentenceSpeechRecognition(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::asr::v1::Response, ::asr::v1::Request>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestOneSentenceSpeechRecognition(::grpc::ServerContext* context, ::grpc::ServerAsyncReaderWriter< ::asr::v1::Response, ::asr::v1::Request>* stream, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncBidiStreaming(0, context, stream, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_RealTimeSpeechRecognition : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_RealTimeSpeechRecognition() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_RealTimeSpeechRecognition() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RealTimeSpeechRecognition(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::asr::v1::Response, ::asr::v1::Request>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestRealTimeSpeechRecognition(::grpc::ServerContext* context, ::grpc::ServerAsyncReaderWriter< ::asr::v1::Response, ::asr::v1::Request>* stream, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncBidiStreaming(1, context, stream, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_OneSentenceSpeechRecognition<WithAsyncMethod_RealTimeSpeechRecognition<Service > > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_OneSentenceSpeechRecognition : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_OneSentenceSpeechRecognition() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackBidiHandler< ::asr::v1::Request, ::asr::v1::Response>(
            [this](
                   ::grpc::CallbackServerContext* context) { return this->OneSentenceSpeechRecognition(context); }));
    }
    ~WithCallbackMethod_OneSentenceSpeechRecognition() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status OneSentenceSpeechRecognition(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::asr::v1::Response, ::asr::v1::Request>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerBidiReactor< ::asr::v1::Request, ::asr::v1::Response>* OneSentenceSpeechRecognition(
      ::grpc::CallbackServerContext* /*context*/)
      { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_RealTimeSpeechRecognition : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_RealTimeSpeechRecognition() {
      ::grpc::Service::MarkMethodCallback(1,
          new ::grpc::internal::CallbackBidiHandler< ::asr::v1::Request, ::asr::v1::Response>(
            [this](
                   ::grpc::CallbackServerContext* context) { return this->RealTimeSpeechRecognition(context); }));
    }
    ~WithCallbackMethod_RealTimeSpeechRecognition() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RealTimeSpeechRecognition(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::asr::v1::Response, ::asr::v1::Request>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerBidiReactor< ::asr::v1::Request, ::asr::v1::Response>* RealTimeSpeechRecognition(
      ::grpc::CallbackServerContext* /*context*/)
      { return nullptr; }
  };
  typedef WithCallbackMethod_OneSentenceSpeechRecognition<WithCallbackMethod_RealTimeSpeechRecognition<Service > > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_OneSentenceSpeechRecognition : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_OneSentenceSpeechRecognition() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_OneSentenceSpeechRecognition() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status OneSentenceSpeechRecognition(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::asr::v1::Response, ::asr::v1::Request>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_RealTimeSpeechRecognition : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_RealTimeSpeechRecognition() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_RealTimeSpeechRecognition() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RealTimeSpeechRecognition(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::asr::v1::Response, ::asr::v1::Request>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_OneSentenceSpeechRecognition : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_OneSentenceSpeechRecognition() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_OneSentenceSpeechRecognition() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status OneSentenceSpeechRecognition(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::asr::v1::Response, ::asr::v1::Request>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestOneSentenceSpeechRecognition(::grpc::ServerContext* context, ::grpc::ServerAsyncReaderWriter< ::grpc::ByteBuffer, ::grpc::ByteBuffer>* stream, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncBidiStreaming(0, context, stream, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_RealTimeSpeechRecognition : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_RealTimeSpeechRecognition() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_RealTimeSpeechRecognition() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RealTimeSpeechRecognition(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::asr::v1::Response, ::asr::v1::Request>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestRealTimeSpeechRecognition(::grpc::ServerContext* context, ::grpc::ServerAsyncReaderWriter< ::grpc::ByteBuffer, ::grpc::ByteBuffer>* stream, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncBidiStreaming(1, context, stream, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_OneSentenceSpeechRecognition : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_OneSentenceSpeechRecognition() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackBidiHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context) { return this->OneSentenceSpeechRecognition(context); }));
    }
    ~WithRawCallbackMethod_OneSentenceSpeechRecognition() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status OneSentenceSpeechRecognition(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::asr::v1::Response, ::asr::v1::Request>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerBidiReactor< ::grpc::ByteBuffer, ::grpc::ByteBuffer>* OneSentenceSpeechRecognition(
      ::grpc::CallbackServerContext* /*context*/)
      { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_RealTimeSpeechRecognition : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_RealTimeSpeechRecognition() {
      ::grpc::Service::MarkMethodRawCallback(1,
          new ::grpc::internal::CallbackBidiHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context) { return this->RealTimeSpeechRecognition(context); }));
    }
    ~WithRawCallbackMethod_RealTimeSpeechRecognition() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RealTimeSpeechRecognition(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::asr::v1::Response, ::asr::v1::Request>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerBidiReactor< ::grpc::ByteBuffer, ::grpc::ByteBuffer>* RealTimeSpeechRecognition(
      ::grpc::CallbackServerContext* /*context*/)
      { return nullptr; }
  };
  typedef Service StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef Service StreamedService;
};
// The details of the communication is described in: https://confluence.mthreads.com/pages/viewpage.action?pageId=83871842

}  // namespace v1
}  // namespace asr


#endif  // GRPC_grpc_2fasr_2eproto__INCLUDED
