// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: grpc/asr.proto

#include "grpc/asr.pb.h"
#include "grpc/asr.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace asr {
namespace v1 {

static const char* ASR_method_names[] = {
  "/asr.v1.ASR/OneSentenceSpeechRecognition",
  "/asr.v1.ASR/RealTimeSpeechRecognition",
};

std::unique_ptr< ASR::Stub> ASR::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< ASR::Stub> stub(new ASR::Stub(channel, options));
  return stub;
}

ASR::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_OneSentenceSpeechRecognition_(ASR_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::BIDI_STREAMING, channel)
  , rpcmethod_RealTimeSpeechRecognition_(ASR_method_names[1], options.suffix_for_stats(),::grpc::internal::RpcMethod::BIDI_STREAMING, channel)
  {}

::grpc::ClientReaderWriter< ::asr::v1::Request, ::asr::v1::Response>* ASR::Stub::OneSentenceSpeechRecognitionRaw(::grpc::ClientContext* context) {
  return ::grpc::internal::ClientReaderWriterFactory< ::asr::v1::Request, ::asr::v1::Response>::Create(channel_.get(), rpcmethod_OneSentenceSpeechRecognition_, context);
}

void ASR::Stub::async::OneSentenceSpeechRecognition(::grpc::ClientContext* context, ::grpc::ClientBidiReactor< ::asr::v1::Request,::asr::v1::Response>* reactor) {
  ::grpc::internal::ClientCallbackReaderWriterFactory< ::asr::v1::Request,::asr::v1::Response>::Create(stub_->channel_.get(), stub_->rpcmethod_OneSentenceSpeechRecognition_, context, reactor);
}

::grpc::ClientAsyncReaderWriter< ::asr::v1::Request, ::asr::v1::Response>* ASR::Stub::AsyncOneSentenceSpeechRecognitionRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc::internal::ClientAsyncReaderWriterFactory< ::asr::v1::Request, ::asr::v1::Response>::Create(channel_.get(), cq, rpcmethod_OneSentenceSpeechRecognition_, context, true, tag);
}

::grpc::ClientAsyncReaderWriter< ::asr::v1::Request, ::asr::v1::Response>* ASR::Stub::PrepareAsyncOneSentenceSpeechRecognitionRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncReaderWriterFactory< ::asr::v1::Request, ::asr::v1::Response>::Create(channel_.get(), cq, rpcmethod_OneSentenceSpeechRecognition_, context, false, nullptr);
}

::grpc::ClientReaderWriter< ::asr::v1::Request, ::asr::v1::Response>* ASR::Stub::RealTimeSpeechRecognitionRaw(::grpc::ClientContext* context) {
  return ::grpc::internal::ClientReaderWriterFactory< ::asr::v1::Request, ::asr::v1::Response>::Create(channel_.get(), rpcmethod_RealTimeSpeechRecognition_, context);
}

void ASR::Stub::async::RealTimeSpeechRecognition(::grpc::ClientContext* context, ::grpc::ClientBidiReactor< ::asr::v1::Request,::asr::v1::Response>* reactor) {
  ::grpc::internal::ClientCallbackReaderWriterFactory< ::asr::v1::Request,::asr::v1::Response>::Create(stub_->channel_.get(), stub_->rpcmethod_RealTimeSpeechRecognition_, context, reactor);
}

::grpc::ClientAsyncReaderWriter< ::asr::v1::Request, ::asr::v1::Response>* ASR::Stub::AsyncRealTimeSpeechRecognitionRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc::internal::ClientAsyncReaderWriterFactory< ::asr::v1::Request, ::asr::v1::Response>::Create(channel_.get(), cq, rpcmethod_RealTimeSpeechRecognition_, context, true, tag);
}

::grpc::ClientAsyncReaderWriter< ::asr::v1::Request, ::asr::v1::Response>* ASR::Stub::PrepareAsyncRealTimeSpeechRecognitionRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncReaderWriterFactory< ::asr::v1::Request, ::asr::v1::Response>::Create(channel_.get(), cq, rpcmethod_RealTimeSpeechRecognition_, context, false, nullptr);
}

ASR::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      ASR_method_names[0],
      ::grpc::internal::RpcMethod::BIDI_STREAMING,
      new ::grpc::internal::BidiStreamingHandler< ASR::Service, ::asr::v1::Request, ::asr::v1::Response>(
          [](ASR::Service* service,
             ::grpc::ServerContext* ctx,
             ::grpc::ServerReaderWriter<::asr::v1::Response,
             ::asr::v1::Request>* stream) {
               return service->OneSentenceSpeechRecognition(ctx, stream);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      ASR_method_names[1],
      ::grpc::internal::RpcMethod::BIDI_STREAMING,
      new ::grpc::internal::BidiStreamingHandler< ASR::Service, ::asr::v1::Request, ::asr::v1::Response>(
          [](ASR::Service* service,
             ::grpc::ServerContext* ctx,
             ::grpc::ServerReaderWriter<::asr::v1::Response,
             ::asr::v1::Request>* stream) {
               return service->RealTimeSpeechRecognition(ctx, stream);
             }, this)));
}

ASR::Service::~Service() {
}

::grpc::Status ASR::Service::OneSentenceSpeechRecognition(::grpc::ServerContext* context, ::grpc::ServerReaderWriter< ::asr::v1::Response, ::asr::v1::Request>* stream) {
  (void) context;
  (void) stream;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status ASR::Service::RealTimeSpeechRecognition(::grpc::ServerContext* context, ::grpc::ServerReaderWriter< ::asr::v1::Response, ::asr::v1::Request>* stream) {
  (void) context;
  (void) stream;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace asr
}  // namespace v1

