// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: grpc/asr.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_grpc_2fasr_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_grpc_2fasr_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_grpc_2fasr_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_grpc_2fasr_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_grpc_2fasr_2eproto;
namespace asr {
namespace v1 {
class OneBest;
struct OneBestDefaultTypeInternal;
extern OneBestDefaultTypeInternal _OneBest_default_instance_;
class OnePiece;
struct OnePieceDefaultTypeInternal;
extern OnePieceDefaultTypeInternal _OnePiece_default_instance_;
class Request;
struct RequestDefaultTypeInternal;
extern RequestDefaultTypeInternal _Request_default_instance_;
class Request_DecodeConfig;
struct Request_DecodeConfigDefaultTypeInternal;
extern Request_DecodeConfigDefaultTypeInternal _Request_DecodeConfig_default_instance_;
class Response;
struct ResponseDefaultTypeInternal;
extern ResponseDefaultTypeInternal _Response_default_instance_;
class Response_Header;
struct Response_HeaderDefaultTypeInternal;
extern Response_HeaderDefaultTypeInternal _Response_Header_default_instance_;
class Response_Payload;
struct Response_PayloadDefaultTypeInternal;
extern Response_PayloadDefaultTypeInternal _Response_Payload_default_instance_;
}  // namespace v1
}  // namespace asr
PROTOBUF_NAMESPACE_OPEN
template<> ::asr::v1::OneBest* Arena::CreateMaybeMessage<::asr::v1::OneBest>(Arena*);
template<> ::asr::v1::OnePiece* Arena::CreateMaybeMessage<::asr::v1::OnePiece>(Arena*);
template<> ::asr::v1::Request* Arena::CreateMaybeMessage<::asr::v1::Request>(Arena*);
template<> ::asr::v1::Request_DecodeConfig* Arena::CreateMaybeMessage<::asr::v1::Request_DecodeConfig>(Arena*);
template<> ::asr::v1::Response* Arena::CreateMaybeMessage<::asr::v1::Response>(Arena*);
template<> ::asr::v1::Response_Header* Arena::CreateMaybeMessage<::asr::v1::Response_Header>(Arena*);
template<> ::asr::v1::Response_Payload* Arena::CreateMaybeMessage<::asr::v1::Response_Payload>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace asr {
namespace v1 {

enum Response_Status : int {
  Response_Status_UNKNOWN_STATUS = 0,
  Response_Status_OK = 1,
  Response_Status_FAILED = 2,
  Response_Status_Response_Status_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  Response_Status_Response_Status_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool Response_Status_IsValid(int value);
constexpr Response_Status Response_Status_Status_MIN = Response_Status_UNKNOWN_STATUS;
constexpr Response_Status Response_Status_Status_MAX = Response_Status_FAILED;
constexpr int Response_Status_Status_ARRAYSIZE = Response_Status_Status_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* Response_Status_descriptor();
template<typename T>
inline const std::string& Response_Status_Name(T enum_t_value) {
  static_assert(::std::is_same<T, Response_Status>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function Response_Status_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    Response_Status_descriptor(), enum_t_value);
}
inline bool Response_Status_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, Response_Status* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<Response_Status>(
    Response_Status_descriptor(), name, value);
}
enum Response_Type : int {
  Response_Type_UNKNOWN_TYPE = 0,
  Response_Type_SENTENCE_CHANGED = 1,
  Response_Type_SENTENCE_END = 2,
  Response_Type_COMPLETED = 3,
  Response_Type_Response_Type_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  Response_Type_Response_Type_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool Response_Type_IsValid(int value);
constexpr Response_Type Response_Type_Type_MIN = Response_Type_UNKNOWN_TYPE;
constexpr Response_Type Response_Type_Type_MAX = Response_Type_COMPLETED;
constexpr int Response_Type_Type_ARRAYSIZE = Response_Type_Type_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* Response_Type_descriptor();
template<typename T>
inline const std::string& Response_Type_Name(T enum_t_value) {
  static_assert(::std::is_same<T, Response_Type>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function Response_Type_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    Response_Type_descriptor(), enum_t_value);
}
inline bool Response_Type_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, Response_Type* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<Response_Type>(
    Response_Type_descriptor(), name, value);
}
// ===================================================================

class Request_DecodeConfig final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:asr.v1.Request.DecodeConfig) */ {
 public:
  inline Request_DecodeConfig() : Request_DecodeConfig(nullptr) {}
  ~Request_DecodeConfig() override;
  explicit PROTOBUF_CONSTEXPR Request_DecodeConfig(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Request_DecodeConfig(const Request_DecodeConfig& from);
  Request_DecodeConfig(Request_DecodeConfig&& from) noexcept
    : Request_DecodeConfig() {
    *this = ::std::move(from);
  }

  inline Request_DecodeConfig& operator=(const Request_DecodeConfig& from) {
    CopyFrom(from);
    return *this;
  }
  inline Request_DecodeConfig& operator=(Request_DecodeConfig&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Request_DecodeConfig& default_instance() {
    return *internal_default_instance();
  }
  static inline const Request_DecodeConfig* internal_default_instance() {
    return reinterpret_cast<const Request_DecodeConfig*>(
               &_Request_DecodeConfig_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(Request_DecodeConfig& a, Request_DecodeConfig& b) {
    a.Swap(&b);
  }
  inline void Swap(Request_DecodeConfig* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Request_DecodeConfig* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Request_DecodeConfig* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Request_DecodeConfig>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const Request_DecodeConfig& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const Request_DecodeConfig& from) {
    Request_DecodeConfig::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Request_DecodeConfig* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "asr.v1.Request.DecodeConfig";
  }
  protected:
  explicit Request_DecodeConfig(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kReqIdFieldNumber = 1,
    kNbestFieldNumber = 2,
  };
  // string req_id = 1;
  void clear_req_id();
  const std::string& req_id() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_req_id(ArgT0&& arg0, ArgT... args);
  std::string* mutable_req_id();
  PROTOBUF_NODISCARD std::string* release_req_id();
  void set_allocated_req_id(std::string* req_id);
  private:
  const std::string& _internal_req_id() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_req_id(const std::string& value);
  std::string* _internal_mutable_req_id();
  public:

  // int32 nbest = 2;
  void clear_nbest();
  int32_t nbest() const;
  void set_nbest(int32_t value);
  private:
  int32_t _internal_nbest() const;
  void _internal_set_nbest(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:asr.v1.Request.DecodeConfig)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr req_id_;
    int32_t nbest_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_grpc_2fasr_2eproto;
};
// -------------------------------------------------------------------

class Request final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:asr.v1.Request) */ {
 public:
  inline Request() : Request(nullptr) {}
  ~Request() override;
  explicit PROTOBUF_CONSTEXPR Request(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Request(const Request& from);
  Request(Request&& from) noexcept
    : Request() {
    *this = ::std::move(from);
  }

  inline Request& operator=(const Request& from) {
    CopyFrom(from);
    return *this;
  }
  inline Request& operator=(Request&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Request& default_instance() {
    return *internal_default_instance();
  }
  enum PayloadCase {
    kDecodeConfig = 1,
    kAudioData = 2,
    PAYLOAD_NOT_SET = 0,
  };

  static inline const Request* internal_default_instance() {
    return reinterpret_cast<const Request*>(
               &_Request_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(Request& a, Request& b) {
    a.Swap(&b);
  }
  inline void Swap(Request* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Request* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Request* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Request>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const Request& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const Request& from) {
    Request::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Request* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "asr.v1.Request";
  }
  protected:
  explicit Request(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  typedef Request_DecodeConfig DecodeConfig;

  // accessors -------------------------------------------------------

  enum : int {
    kDecodeConfigFieldNumber = 1,
    kAudioDataFieldNumber = 2,
  };
  // .asr.v1.Request.DecodeConfig decode_config = 1;
  bool has_decode_config() const;
  private:
  bool _internal_has_decode_config() const;
  public:
  void clear_decode_config();
  const ::asr::v1::Request_DecodeConfig& decode_config() const;
  PROTOBUF_NODISCARD ::asr::v1::Request_DecodeConfig* release_decode_config();
  ::asr::v1::Request_DecodeConfig* mutable_decode_config();
  void set_allocated_decode_config(::asr::v1::Request_DecodeConfig* decode_config);
  private:
  const ::asr::v1::Request_DecodeConfig& _internal_decode_config() const;
  ::asr::v1::Request_DecodeConfig* _internal_mutable_decode_config();
  public:
  void unsafe_arena_set_allocated_decode_config(
      ::asr::v1::Request_DecodeConfig* decode_config);
  ::asr::v1::Request_DecodeConfig* unsafe_arena_release_decode_config();

  // bytes audio_data = 2;
  bool has_audio_data() const;
  private:
  bool _internal_has_audio_data() const;
  public:
  void clear_audio_data();
  const std::string& audio_data() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_audio_data(ArgT0&& arg0, ArgT... args);
  std::string* mutable_audio_data();
  PROTOBUF_NODISCARD std::string* release_audio_data();
  void set_allocated_audio_data(std::string* audio_data);
  private:
  const std::string& _internal_audio_data() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_audio_data(const std::string& value);
  std::string* _internal_mutable_audio_data();
  public:

  void clear_payload();
  PayloadCase payload_case() const;
  // @@protoc_insertion_point(class_scope:asr.v1.Request)
 private:
  class _Internal;
  void set_has_decode_config();
  void set_has_audio_data();

  inline bool has_payload() const;
  inline void clear_has_payload();

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    union PayloadUnion {
      constexpr PayloadUnion() : _constinit_{} {}
        ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized _constinit_;
      ::asr::v1::Request_DecodeConfig* decode_config_;
      ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr audio_data_;
    } payload_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
    uint32_t _oneof_case_[1];

  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_grpc_2fasr_2eproto;
};
// -------------------------------------------------------------------

class OneBest final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:asr.v1.OneBest) */ {
 public:
  inline OneBest() : OneBest(nullptr) {}
  ~OneBest() override;
  explicit PROTOBUF_CONSTEXPR OneBest(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  OneBest(const OneBest& from);
  OneBest(OneBest&& from) noexcept
    : OneBest() {
    *this = ::std::move(from);
  }

  inline OneBest& operator=(const OneBest& from) {
    CopyFrom(from);
    return *this;
  }
  inline OneBest& operator=(OneBest&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const OneBest& default_instance() {
    return *internal_default_instance();
  }
  static inline const OneBest* internal_default_instance() {
    return reinterpret_cast<const OneBest*>(
               &_OneBest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(OneBest& a, OneBest& b) {
    a.Swap(&b);
  }
  inline void Swap(OneBest* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(OneBest* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  OneBest* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<OneBest>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const OneBest& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const OneBest& from) {
    OneBest::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(OneBest* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "asr.v1.OneBest";
  }
  protected:
  explicit OneBest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kWordpiecesFieldNumber = 2,
    kSentenceFieldNumber = 1,
  };
  // repeated .asr.v1.OnePiece wordpieces = 2;
  int wordpieces_size() const;
  private:
  int _internal_wordpieces_size() const;
  public:
  void clear_wordpieces();
  ::asr::v1::OnePiece* mutable_wordpieces(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::asr::v1::OnePiece >*
      mutable_wordpieces();
  private:
  const ::asr::v1::OnePiece& _internal_wordpieces(int index) const;
  ::asr::v1::OnePiece* _internal_add_wordpieces();
  public:
  const ::asr::v1::OnePiece& wordpieces(int index) const;
  ::asr::v1::OnePiece* add_wordpieces();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::asr::v1::OnePiece >&
      wordpieces() const;

  // string sentence = 1;
  void clear_sentence();
  const std::string& sentence() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_sentence(ArgT0&& arg0, ArgT... args);
  std::string* mutable_sentence();
  PROTOBUF_NODISCARD std::string* release_sentence();
  void set_allocated_sentence(std::string* sentence);
  private:
  const std::string& _internal_sentence() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_sentence(const std::string& value);
  std::string* _internal_mutable_sentence();
  public:

  // @@protoc_insertion_point(class_scope:asr.v1.OneBest)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::asr::v1::OnePiece > wordpieces_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr sentence_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_grpc_2fasr_2eproto;
};
// -------------------------------------------------------------------

class OnePiece final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:asr.v1.OnePiece) */ {
 public:
  inline OnePiece() : OnePiece(nullptr) {}
  ~OnePiece() override;
  explicit PROTOBUF_CONSTEXPR OnePiece(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  OnePiece(const OnePiece& from);
  OnePiece(OnePiece&& from) noexcept
    : OnePiece() {
    *this = ::std::move(from);
  }

  inline OnePiece& operator=(const OnePiece& from) {
    CopyFrom(from);
    return *this;
  }
  inline OnePiece& operator=(OnePiece&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const OnePiece& default_instance() {
    return *internal_default_instance();
  }
  static inline const OnePiece* internal_default_instance() {
    return reinterpret_cast<const OnePiece*>(
               &_OnePiece_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(OnePiece& a, OnePiece& b) {
    a.Swap(&b);
  }
  inline void Swap(OnePiece* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(OnePiece* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  OnePiece* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<OnePiece>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const OnePiece& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const OnePiece& from) {
    OnePiece::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(OnePiece* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "asr.v1.OnePiece";
  }
  protected:
  explicit OnePiece(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kWordFieldNumber = 1,
    kStartFieldNumber = 2,
    kEndFieldNumber = 3,
  };
  // string word = 1;
  void clear_word();
  const std::string& word() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_word(ArgT0&& arg0, ArgT... args);
  std::string* mutable_word();
  PROTOBUF_NODISCARD std::string* release_word();
  void set_allocated_word(std::string* word);
  private:
  const std::string& _internal_word() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_word(const std::string& value);
  std::string* _internal_mutable_word();
  public:

  // int32 start = 2;
  void clear_start();
  int32_t start() const;
  void set_start(int32_t value);
  private:
  int32_t _internal_start() const;
  void _internal_set_start(int32_t value);
  public:

  // int32 end = 3;
  void clear_end();
  int32_t end() const;
  void set_end(int32_t value);
  private:
  int32_t _internal_end() const;
  void _internal_set_end(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:asr.v1.OnePiece)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr word_;
    int32_t start_;
    int32_t end_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_grpc_2fasr_2eproto;
};
// -------------------------------------------------------------------

class Response_Header final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:asr.v1.Response.Header) */ {
 public:
  inline Response_Header() : Response_Header(nullptr) {}
  ~Response_Header() override;
  explicit PROTOBUF_CONSTEXPR Response_Header(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Response_Header(const Response_Header& from);
  Response_Header(Response_Header&& from) noexcept
    : Response_Header() {
    *this = ::std::move(from);
  }

  inline Response_Header& operator=(const Response_Header& from) {
    CopyFrom(from);
    return *this;
  }
  inline Response_Header& operator=(Response_Header&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Response_Header& default_instance() {
    return *internal_default_instance();
  }
  static inline const Response_Header* internal_default_instance() {
    return reinterpret_cast<const Response_Header*>(
               &_Response_Header_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    4;

  friend void swap(Response_Header& a, Response_Header& b) {
    a.Swap(&b);
  }
  inline void Swap(Response_Header* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Response_Header* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Response_Header* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Response_Header>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const Response_Header& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const Response_Header& from) {
    Response_Header::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Response_Header* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "asr.v1.Response.Header";
  }
  protected:
  explicit Response_Header(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kStatusFieldNumber = 1,
    kTypeFieldNumber = 2,
  };
  // .asr.v1.Response.Status status = 1;
  void clear_status();
  ::asr::v1::Response_Status status() const;
  void set_status(::asr::v1::Response_Status value);
  private:
  ::asr::v1::Response_Status _internal_status() const;
  void _internal_set_status(::asr::v1::Response_Status value);
  public:

  // .asr.v1.Response.Type type = 2;
  void clear_type();
  ::asr::v1::Response_Type type() const;
  void set_type(::asr::v1::Response_Type value);
  private:
  ::asr::v1::Response_Type _internal_type() const;
  void _internal_set_type(::asr::v1::Response_Type value);
  public:

  // @@protoc_insertion_point(class_scope:asr.v1.Response.Header)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    int status_;
    int type_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_grpc_2fasr_2eproto;
};
// -------------------------------------------------------------------

class Response_Payload final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:asr.v1.Response.Payload) */ {
 public:
  inline Response_Payload() : Response_Payload(nullptr) {}
  ~Response_Payload() override;
  explicit PROTOBUF_CONSTEXPR Response_Payload(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Response_Payload(const Response_Payload& from);
  Response_Payload(Response_Payload&& from) noexcept
    : Response_Payload() {
    *this = ::std::move(from);
  }

  inline Response_Payload& operator=(const Response_Payload& from) {
    CopyFrom(from);
    return *this;
  }
  inline Response_Payload& operator=(Response_Payload&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Response_Payload& default_instance() {
    return *internal_default_instance();
  }
  static inline const Response_Payload* internal_default_instance() {
    return reinterpret_cast<const Response_Payload*>(
               &_Response_Payload_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    5;

  friend void swap(Response_Payload& a, Response_Payload& b) {
    a.Swap(&b);
  }
  inline void Swap(Response_Payload* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Response_Payload* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Response_Payload* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Response_Payload>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const Response_Payload& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const Response_Payload& from) {
    Response_Payload::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Response_Payload* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "asr.v1.Response.Payload";
  }
  protected:
  explicit Response_Payload(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kResultFieldNumber = 1,
    kTextFieldNumber = 2,
  };
  // repeated .asr.v1.OneBest result = 1;
  int result_size() const;
  private:
  int _internal_result_size() const;
  public:
  void clear_result();
  ::asr::v1::OneBest* mutable_result(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::asr::v1::OneBest >*
      mutable_result();
  private:
  const ::asr::v1::OneBest& _internal_result(int index) const;
  ::asr::v1::OneBest* _internal_add_result();
  public:
  const ::asr::v1::OneBest& result(int index) const;
  ::asr::v1::OneBest* add_result();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::asr::v1::OneBest >&
      result() const;

  // string text = 2;
  void clear_text();
  const std::string& text() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_text(ArgT0&& arg0, ArgT... args);
  std::string* mutable_text();
  PROTOBUF_NODISCARD std::string* release_text();
  void set_allocated_text(std::string* text);
  private:
  const std::string& _internal_text() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_text(const std::string& value);
  std::string* _internal_mutable_text();
  public:

  // @@protoc_insertion_point(class_scope:asr.v1.Response.Payload)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::asr::v1::OneBest > result_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr text_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_grpc_2fasr_2eproto;
};
// -------------------------------------------------------------------

class Response final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:asr.v1.Response) */ {
 public:
  inline Response() : Response(nullptr) {}
  ~Response() override;
  explicit PROTOBUF_CONSTEXPR Response(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Response(const Response& from);
  Response(Response&& from) noexcept
    : Response() {
    *this = ::std::move(from);
  }

  inline Response& operator=(const Response& from) {
    CopyFrom(from);
    return *this;
  }
  inline Response& operator=(Response&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Response& default_instance() {
    return *internal_default_instance();
  }
  static inline const Response* internal_default_instance() {
    return reinterpret_cast<const Response*>(
               &_Response_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    6;

  friend void swap(Response& a, Response& b) {
    a.Swap(&b);
  }
  inline void Swap(Response* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Response* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Response* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Response>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const Response& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const Response& from) {
    Response::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Response* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "asr.v1.Response";
  }
  protected:
  explicit Response(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  typedef Response_Header Header;
  typedef Response_Payload Payload;

  typedef Response_Status Status;
  static constexpr Status UNKNOWN_STATUS =
    Response_Status_UNKNOWN_STATUS;
  static constexpr Status OK =
    Response_Status_OK;
  static constexpr Status FAILED =
    Response_Status_FAILED;
  static inline bool Status_IsValid(int value) {
    return Response_Status_IsValid(value);
  }
  static constexpr Status Status_MIN =
    Response_Status_Status_MIN;
  static constexpr Status Status_MAX =
    Response_Status_Status_MAX;
  static constexpr int Status_ARRAYSIZE =
    Response_Status_Status_ARRAYSIZE;
  static inline const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor*
  Status_descriptor() {
    return Response_Status_descriptor();
  }
  template<typename T>
  static inline const std::string& Status_Name(T enum_t_value) {
    static_assert(::std::is_same<T, Status>::value ||
      ::std::is_integral<T>::value,
      "Incorrect type passed to function Status_Name.");
    return Response_Status_Name(enum_t_value);
  }
  static inline bool Status_Parse(::PROTOBUF_NAMESPACE_ID::ConstStringParam name,
      Status* value) {
    return Response_Status_Parse(name, value);
  }

  typedef Response_Type Type;
  static constexpr Type UNKNOWN_TYPE =
    Response_Type_UNKNOWN_TYPE;
  static constexpr Type SENTENCE_CHANGED =
    Response_Type_SENTENCE_CHANGED;
  static constexpr Type SENTENCE_END =
    Response_Type_SENTENCE_END;
  static constexpr Type COMPLETED =
    Response_Type_COMPLETED;
  static inline bool Type_IsValid(int value) {
    return Response_Type_IsValid(value);
  }
  static constexpr Type Type_MIN =
    Response_Type_Type_MIN;
  static constexpr Type Type_MAX =
    Response_Type_Type_MAX;
  static constexpr int Type_ARRAYSIZE =
    Response_Type_Type_ARRAYSIZE;
  static inline const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor*
  Type_descriptor() {
    return Response_Type_descriptor();
  }
  template<typename T>
  static inline const std::string& Type_Name(T enum_t_value) {
    static_assert(::std::is_same<T, Type>::value ||
      ::std::is_integral<T>::value,
      "Incorrect type passed to function Type_Name.");
    return Response_Type_Name(enum_t_value);
  }
  static inline bool Type_Parse(::PROTOBUF_NAMESPACE_ID::ConstStringParam name,
      Type* value) {
    return Response_Type_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  enum : int {
    kHeaderFieldNumber = 1,
    kPayloadFieldNumber = 2,
  };
  // .asr.v1.Response.Header header = 1;
  bool has_header() const;
  private:
  bool _internal_has_header() const;
  public:
  void clear_header();
  const ::asr::v1::Response_Header& header() const;
  PROTOBUF_NODISCARD ::asr::v1::Response_Header* release_header();
  ::asr::v1::Response_Header* mutable_header();
  void set_allocated_header(::asr::v1::Response_Header* header);
  private:
  const ::asr::v1::Response_Header& _internal_header() const;
  ::asr::v1::Response_Header* _internal_mutable_header();
  public:
  void unsafe_arena_set_allocated_header(
      ::asr::v1::Response_Header* header);
  ::asr::v1::Response_Header* unsafe_arena_release_header();

  // .asr.v1.Response.Payload payload = 2;
  bool has_payload() const;
  private:
  bool _internal_has_payload() const;
  public:
  void clear_payload();
  const ::asr::v1::Response_Payload& payload() const;
  PROTOBUF_NODISCARD ::asr::v1::Response_Payload* release_payload();
  ::asr::v1::Response_Payload* mutable_payload();
  void set_allocated_payload(::asr::v1::Response_Payload* payload);
  private:
  const ::asr::v1::Response_Payload& _internal_payload() const;
  ::asr::v1::Response_Payload* _internal_mutable_payload();
  public:
  void unsafe_arena_set_allocated_payload(
      ::asr::v1::Response_Payload* payload);
  ::asr::v1::Response_Payload* unsafe_arena_release_payload();

  // @@protoc_insertion_point(class_scope:asr.v1.Response)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::asr::v1::Response_Header* header_;
    ::asr::v1::Response_Payload* payload_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_grpc_2fasr_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// Request_DecodeConfig

// string req_id = 1;
inline void Request_DecodeConfig::clear_req_id() {
  _impl_.req_id_.ClearToEmpty();
}
inline const std::string& Request_DecodeConfig::req_id() const {
  // @@protoc_insertion_point(field_get:asr.v1.Request.DecodeConfig.req_id)
  return _internal_req_id();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void Request_DecodeConfig::set_req_id(ArgT0&& arg0, ArgT... args) {
 
 _impl_.req_id_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:asr.v1.Request.DecodeConfig.req_id)
}
inline std::string* Request_DecodeConfig::mutable_req_id() {
  std::string* _s = _internal_mutable_req_id();
  // @@protoc_insertion_point(field_mutable:asr.v1.Request.DecodeConfig.req_id)
  return _s;
}
inline const std::string& Request_DecodeConfig::_internal_req_id() const {
  return _impl_.req_id_.Get();
}
inline void Request_DecodeConfig::_internal_set_req_id(const std::string& value) {
  
  _impl_.req_id_.Set(value, GetArenaForAllocation());
}
inline std::string* Request_DecodeConfig::_internal_mutable_req_id() {
  
  return _impl_.req_id_.Mutable(GetArenaForAllocation());
}
inline std::string* Request_DecodeConfig::release_req_id() {
  // @@protoc_insertion_point(field_release:asr.v1.Request.DecodeConfig.req_id)
  return _impl_.req_id_.Release();
}
inline void Request_DecodeConfig::set_allocated_req_id(std::string* req_id) {
  if (req_id != nullptr) {
    
  } else {
    
  }
  _impl_.req_id_.SetAllocated(req_id, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.req_id_.IsDefault()) {
    _impl_.req_id_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:asr.v1.Request.DecodeConfig.req_id)
}

// int32 nbest = 2;
inline void Request_DecodeConfig::clear_nbest() {
  _impl_.nbest_ = 0;
}
inline int32_t Request_DecodeConfig::_internal_nbest() const {
  return _impl_.nbest_;
}
inline int32_t Request_DecodeConfig::nbest() const {
  // @@protoc_insertion_point(field_get:asr.v1.Request.DecodeConfig.nbest)
  return _internal_nbest();
}
inline void Request_DecodeConfig::_internal_set_nbest(int32_t value) {
  
  _impl_.nbest_ = value;
}
inline void Request_DecodeConfig::set_nbest(int32_t value) {
  _internal_set_nbest(value);
  // @@protoc_insertion_point(field_set:asr.v1.Request.DecodeConfig.nbest)
}

// -------------------------------------------------------------------

// Request

// .asr.v1.Request.DecodeConfig decode_config = 1;
inline bool Request::_internal_has_decode_config() const {
  return payload_case() == kDecodeConfig;
}
inline bool Request::has_decode_config() const {
  return _internal_has_decode_config();
}
inline void Request::set_has_decode_config() {
  _impl_._oneof_case_[0] = kDecodeConfig;
}
inline void Request::clear_decode_config() {
  if (_internal_has_decode_config()) {
    if (GetArenaForAllocation() == nullptr) {
      delete _impl_.payload_.decode_config_;
    }
    clear_has_payload();
  }
}
inline ::asr::v1::Request_DecodeConfig* Request::release_decode_config() {
  // @@protoc_insertion_point(field_release:asr.v1.Request.decode_config)
  if (_internal_has_decode_config()) {
    clear_has_payload();
    ::asr::v1::Request_DecodeConfig* temp = _impl_.payload_.decode_config_;
    if (GetArenaForAllocation() != nullptr) {
      temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
    }
    _impl_.payload_.decode_config_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::asr::v1::Request_DecodeConfig& Request::_internal_decode_config() const {
  return _internal_has_decode_config()
      ? *_impl_.payload_.decode_config_
      : reinterpret_cast< ::asr::v1::Request_DecodeConfig&>(::asr::v1::_Request_DecodeConfig_default_instance_);
}
inline const ::asr::v1::Request_DecodeConfig& Request::decode_config() const {
  // @@protoc_insertion_point(field_get:asr.v1.Request.decode_config)
  return _internal_decode_config();
}
inline ::asr::v1::Request_DecodeConfig* Request::unsafe_arena_release_decode_config() {
  // @@protoc_insertion_point(field_unsafe_arena_release:asr.v1.Request.decode_config)
  if (_internal_has_decode_config()) {
    clear_has_payload();
    ::asr::v1::Request_DecodeConfig* temp = _impl_.payload_.decode_config_;
    _impl_.payload_.decode_config_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void Request::unsafe_arena_set_allocated_decode_config(::asr::v1::Request_DecodeConfig* decode_config) {
  clear_payload();
  if (decode_config) {
    set_has_decode_config();
    _impl_.payload_.decode_config_ = decode_config;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:asr.v1.Request.decode_config)
}
inline ::asr::v1::Request_DecodeConfig* Request::_internal_mutable_decode_config() {
  if (!_internal_has_decode_config()) {
    clear_payload();
    set_has_decode_config();
    _impl_.payload_.decode_config_ = CreateMaybeMessage< ::asr::v1::Request_DecodeConfig >(GetArenaForAllocation());
  }
  return _impl_.payload_.decode_config_;
}
inline ::asr::v1::Request_DecodeConfig* Request::mutable_decode_config() {
  ::asr::v1::Request_DecodeConfig* _msg = _internal_mutable_decode_config();
  // @@protoc_insertion_point(field_mutable:asr.v1.Request.decode_config)
  return _msg;
}

// bytes audio_data = 2;
inline bool Request::_internal_has_audio_data() const {
  return payload_case() == kAudioData;
}
inline bool Request::has_audio_data() const {
  return _internal_has_audio_data();
}
inline void Request::set_has_audio_data() {
  _impl_._oneof_case_[0] = kAudioData;
}
inline void Request::clear_audio_data() {
  if (_internal_has_audio_data()) {
    _impl_.payload_.audio_data_.Destroy();
    clear_has_payload();
  }
}
inline const std::string& Request::audio_data() const {
  // @@protoc_insertion_point(field_get:asr.v1.Request.audio_data)
  return _internal_audio_data();
}
template <typename ArgT0, typename... ArgT>
inline void Request::set_audio_data(ArgT0&& arg0, ArgT... args) {
  if (!_internal_has_audio_data()) {
    clear_payload();
    set_has_audio_data();
    _impl_.payload_.audio_data_.InitDefault();
  }
  _impl_.payload_.audio_data_.SetBytes( static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:asr.v1.Request.audio_data)
}
inline std::string* Request::mutable_audio_data() {
  std::string* _s = _internal_mutable_audio_data();
  // @@protoc_insertion_point(field_mutable:asr.v1.Request.audio_data)
  return _s;
}
inline const std::string& Request::_internal_audio_data() const {
  if (_internal_has_audio_data()) {
    return _impl_.payload_.audio_data_.Get();
  }
  return ::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited();
}
inline void Request::_internal_set_audio_data(const std::string& value) {
  if (!_internal_has_audio_data()) {
    clear_payload();
    set_has_audio_data();
    _impl_.payload_.audio_data_.InitDefault();
  }
  _impl_.payload_.audio_data_.Set(value, GetArenaForAllocation());
}
inline std::string* Request::_internal_mutable_audio_data() {
  if (!_internal_has_audio_data()) {
    clear_payload();
    set_has_audio_data();
    _impl_.payload_.audio_data_.InitDefault();
  }
  return _impl_.payload_.audio_data_.Mutable(      GetArenaForAllocation());
}
inline std::string* Request::release_audio_data() {
  // @@protoc_insertion_point(field_release:asr.v1.Request.audio_data)
  if (_internal_has_audio_data()) {
    clear_has_payload();
    return _impl_.payload_.audio_data_.Release();
  } else {
    return nullptr;
  }
}
inline void Request::set_allocated_audio_data(std::string* audio_data) {
  if (has_payload()) {
    clear_payload();
  }
  if (audio_data != nullptr) {
    set_has_audio_data();
    _impl_.payload_.audio_data_.InitAllocated(audio_data, GetArenaForAllocation());
  }
  // @@protoc_insertion_point(field_set_allocated:asr.v1.Request.audio_data)
}

inline bool Request::has_payload() const {
  return payload_case() != PAYLOAD_NOT_SET;
}
inline void Request::clear_has_payload() {
  _impl_._oneof_case_[0] = PAYLOAD_NOT_SET;
}
inline Request::PayloadCase Request::payload_case() const {
  return Request::PayloadCase(_impl_._oneof_case_[0]);
}
// -------------------------------------------------------------------

// OneBest

// string sentence = 1;
inline void OneBest::clear_sentence() {
  _impl_.sentence_.ClearToEmpty();
}
inline const std::string& OneBest::sentence() const {
  // @@protoc_insertion_point(field_get:asr.v1.OneBest.sentence)
  return _internal_sentence();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void OneBest::set_sentence(ArgT0&& arg0, ArgT... args) {
 
 _impl_.sentence_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:asr.v1.OneBest.sentence)
}
inline std::string* OneBest::mutable_sentence() {
  std::string* _s = _internal_mutable_sentence();
  // @@protoc_insertion_point(field_mutable:asr.v1.OneBest.sentence)
  return _s;
}
inline const std::string& OneBest::_internal_sentence() const {
  return _impl_.sentence_.Get();
}
inline void OneBest::_internal_set_sentence(const std::string& value) {
  
  _impl_.sentence_.Set(value, GetArenaForAllocation());
}
inline std::string* OneBest::_internal_mutable_sentence() {
  
  return _impl_.sentence_.Mutable(GetArenaForAllocation());
}
inline std::string* OneBest::release_sentence() {
  // @@protoc_insertion_point(field_release:asr.v1.OneBest.sentence)
  return _impl_.sentence_.Release();
}
inline void OneBest::set_allocated_sentence(std::string* sentence) {
  if (sentence != nullptr) {
    
  } else {
    
  }
  _impl_.sentence_.SetAllocated(sentence, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.sentence_.IsDefault()) {
    _impl_.sentence_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:asr.v1.OneBest.sentence)
}

// repeated .asr.v1.OnePiece wordpieces = 2;
inline int OneBest::_internal_wordpieces_size() const {
  return _impl_.wordpieces_.size();
}
inline int OneBest::wordpieces_size() const {
  return _internal_wordpieces_size();
}
inline void OneBest::clear_wordpieces() {
  _impl_.wordpieces_.Clear();
}
inline ::asr::v1::OnePiece* OneBest::mutable_wordpieces(int index) {
  // @@protoc_insertion_point(field_mutable:asr.v1.OneBest.wordpieces)
  return _impl_.wordpieces_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::asr::v1::OnePiece >*
OneBest::mutable_wordpieces() {
  // @@protoc_insertion_point(field_mutable_list:asr.v1.OneBest.wordpieces)
  return &_impl_.wordpieces_;
}
inline const ::asr::v1::OnePiece& OneBest::_internal_wordpieces(int index) const {
  return _impl_.wordpieces_.Get(index);
}
inline const ::asr::v1::OnePiece& OneBest::wordpieces(int index) const {
  // @@protoc_insertion_point(field_get:asr.v1.OneBest.wordpieces)
  return _internal_wordpieces(index);
}
inline ::asr::v1::OnePiece* OneBest::_internal_add_wordpieces() {
  return _impl_.wordpieces_.Add();
}
inline ::asr::v1::OnePiece* OneBest::add_wordpieces() {
  ::asr::v1::OnePiece* _add = _internal_add_wordpieces();
  // @@protoc_insertion_point(field_add:asr.v1.OneBest.wordpieces)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::asr::v1::OnePiece >&
OneBest::wordpieces() const {
  // @@protoc_insertion_point(field_list:asr.v1.OneBest.wordpieces)
  return _impl_.wordpieces_;
}

// -------------------------------------------------------------------

// OnePiece

// string word = 1;
inline void OnePiece::clear_word() {
  _impl_.word_.ClearToEmpty();
}
inline const std::string& OnePiece::word() const {
  // @@protoc_insertion_point(field_get:asr.v1.OnePiece.word)
  return _internal_word();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void OnePiece::set_word(ArgT0&& arg0, ArgT... args) {
 
 _impl_.word_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:asr.v1.OnePiece.word)
}
inline std::string* OnePiece::mutable_word() {
  std::string* _s = _internal_mutable_word();
  // @@protoc_insertion_point(field_mutable:asr.v1.OnePiece.word)
  return _s;
}
inline const std::string& OnePiece::_internal_word() const {
  return _impl_.word_.Get();
}
inline void OnePiece::_internal_set_word(const std::string& value) {
  
  _impl_.word_.Set(value, GetArenaForAllocation());
}
inline std::string* OnePiece::_internal_mutable_word() {
  
  return _impl_.word_.Mutable(GetArenaForAllocation());
}
inline std::string* OnePiece::release_word() {
  // @@protoc_insertion_point(field_release:asr.v1.OnePiece.word)
  return _impl_.word_.Release();
}
inline void OnePiece::set_allocated_word(std::string* word) {
  if (word != nullptr) {
    
  } else {
    
  }
  _impl_.word_.SetAllocated(word, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.word_.IsDefault()) {
    _impl_.word_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:asr.v1.OnePiece.word)
}

// int32 start = 2;
inline void OnePiece::clear_start() {
  _impl_.start_ = 0;
}
inline int32_t OnePiece::_internal_start() const {
  return _impl_.start_;
}
inline int32_t OnePiece::start() const {
  // @@protoc_insertion_point(field_get:asr.v1.OnePiece.start)
  return _internal_start();
}
inline void OnePiece::_internal_set_start(int32_t value) {
  
  _impl_.start_ = value;
}
inline void OnePiece::set_start(int32_t value) {
  _internal_set_start(value);
  // @@protoc_insertion_point(field_set:asr.v1.OnePiece.start)
}

// int32 end = 3;
inline void OnePiece::clear_end() {
  _impl_.end_ = 0;
}
inline int32_t OnePiece::_internal_end() const {
  return _impl_.end_;
}
inline int32_t OnePiece::end() const {
  // @@protoc_insertion_point(field_get:asr.v1.OnePiece.end)
  return _internal_end();
}
inline void OnePiece::_internal_set_end(int32_t value) {
  
  _impl_.end_ = value;
}
inline void OnePiece::set_end(int32_t value) {
  _internal_set_end(value);
  // @@protoc_insertion_point(field_set:asr.v1.OnePiece.end)
}

// -------------------------------------------------------------------

// Response_Header

// .asr.v1.Response.Status status = 1;
inline void Response_Header::clear_status() {
  _impl_.status_ = 0;
}
inline ::asr::v1::Response_Status Response_Header::_internal_status() const {
  return static_cast< ::asr::v1::Response_Status >(_impl_.status_);
}
inline ::asr::v1::Response_Status Response_Header::status() const {
  // @@protoc_insertion_point(field_get:asr.v1.Response.Header.status)
  return _internal_status();
}
inline void Response_Header::_internal_set_status(::asr::v1::Response_Status value) {
  
  _impl_.status_ = value;
}
inline void Response_Header::set_status(::asr::v1::Response_Status value) {
  _internal_set_status(value);
  // @@protoc_insertion_point(field_set:asr.v1.Response.Header.status)
}

// .asr.v1.Response.Type type = 2;
inline void Response_Header::clear_type() {
  _impl_.type_ = 0;
}
inline ::asr::v1::Response_Type Response_Header::_internal_type() const {
  return static_cast< ::asr::v1::Response_Type >(_impl_.type_);
}
inline ::asr::v1::Response_Type Response_Header::type() const {
  // @@protoc_insertion_point(field_get:asr.v1.Response.Header.type)
  return _internal_type();
}
inline void Response_Header::_internal_set_type(::asr::v1::Response_Type value) {
  
  _impl_.type_ = value;
}
inline void Response_Header::set_type(::asr::v1::Response_Type value) {
  _internal_set_type(value);
  // @@protoc_insertion_point(field_set:asr.v1.Response.Header.type)
}

// -------------------------------------------------------------------

// Response_Payload

// repeated .asr.v1.OneBest result = 1;
inline int Response_Payload::_internal_result_size() const {
  return _impl_.result_.size();
}
inline int Response_Payload::result_size() const {
  return _internal_result_size();
}
inline void Response_Payload::clear_result() {
  _impl_.result_.Clear();
}
inline ::asr::v1::OneBest* Response_Payload::mutable_result(int index) {
  // @@protoc_insertion_point(field_mutable:asr.v1.Response.Payload.result)
  return _impl_.result_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::asr::v1::OneBest >*
Response_Payload::mutable_result() {
  // @@protoc_insertion_point(field_mutable_list:asr.v1.Response.Payload.result)
  return &_impl_.result_;
}
inline const ::asr::v1::OneBest& Response_Payload::_internal_result(int index) const {
  return _impl_.result_.Get(index);
}
inline const ::asr::v1::OneBest& Response_Payload::result(int index) const {
  // @@protoc_insertion_point(field_get:asr.v1.Response.Payload.result)
  return _internal_result(index);
}
inline ::asr::v1::OneBest* Response_Payload::_internal_add_result() {
  return _impl_.result_.Add();
}
inline ::asr::v1::OneBest* Response_Payload::add_result() {
  ::asr::v1::OneBest* _add = _internal_add_result();
  // @@protoc_insertion_point(field_add:asr.v1.Response.Payload.result)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::asr::v1::OneBest >&
Response_Payload::result() const {
  // @@protoc_insertion_point(field_list:asr.v1.Response.Payload.result)
  return _impl_.result_;
}

// string text = 2;
inline void Response_Payload::clear_text() {
  _impl_.text_.ClearToEmpty();
}
inline const std::string& Response_Payload::text() const {
  // @@protoc_insertion_point(field_get:asr.v1.Response.Payload.text)
  return _internal_text();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void Response_Payload::set_text(ArgT0&& arg0, ArgT... args) {
 
 _impl_.text_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:asr.v1.Response.Payload.text)
}
inline std::string* Response_Payload::mutable_text() {
  std::string* _s = _internal_mutable_text();
  // @@protoc_insertion_point(field_mutable:asr.v1.Response.Payload.text)
  return _s;
}
inline const std::string& Response_Payload::_internal_text() const {
  return _impl_.text_.Get();
}
inline void Response_Payload::_internal_set_text(const std::string& value) {
  
  _impl_.text_.Set(value, GetArenaForAllocation());
}
inline std::string* Response_Payload::_internal_mutable_text() {
  
  return _impl_.text_.Mutable(GetArenaForAllocation());
}
inline std::string* Response_Payload::release_text() {
  // @@protoc_insertion_point(field_release:asr.v1.Response.Payload.text)
  return _impl_.text_.Release();
}
inline void Response_Payload::set_allocated_text(std::string* text) {
  if (text != nullptr) {
    
  } else {
    
  }
  _impl_.text_.SetAllocated(text, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.text_.IsDefault()) {
    _impl_.text_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:asr.v1.Response.Payload.text)
}

// -------------------------------------------------------------------

// Response

// .asr.v1.Response.Header header = 1;
inline bool Response::_internal_has_header() const {
  return this != internal_default_instance() && _impl_.header_ != nullptr;
}
inline bool Response::has_header() const {
  return _internal_has_header();
}
inline void Response::clear_header() {
  if (GetArenaForAllocation() == nullptr && _impl_.header_ != nullptr) {
    delete _impl_.header_;
  }
  _impl_.header_ = nullptr;
}
inline const ::asr::v1::Response_Header& Response::_internal_header() const {
  const ::asr::v1::Response_Header* p = _impl_.header_;
  return p != nullptr ? *p : reinterpret_cast<const ::asr::v1::Response_Header&>(
      ::asr::v1::_Response_Header_default_instance_);
}
inline const ::asr::v1::Response_Header& Response::header() const {
  // @@protoc_insertion_point(field_get:asr.v1.Response.header)
  return _internal_header();
}
inline void Response::unsafe_arena_set_allocated_header(
    ::asr::v1::Response_Header* header) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.header_);
  }
  _impl_.header_ = header;
  if (header) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:asr.v1.Response.header)
}
inline ::asr::v1::Response_Header* Response::release_header() {
  
  ::asr::v1::Response_Header* temp = _impl_.header_;
  _impl_.header_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::asr::v1::Response_Header* Response::unsafe_arena_release_header() {
  // @@protoc_insertion_point(field_release:asr.v1.Response.header)
  
  ::asr::v1::Response_Header* temp = _impl_.header_;
  _impl_.header_ = nullptr;
  return temp;
}
inline ::asr::v1::Response_Header* Response::_internal_mutable_header() {
  
  if (_impl_.header_ == nullptr) {
    auto* p = CreateMaybeMessage<::asr::v1::Response_Header>(GetArenaForAllocation());
    _impl_.header_ = p;
  }
  return _impl_.header_;
}
inline ::asr::v1::Response_Header* Response::mutable_header() {
  ::asr::v1::Response_Header* _msg = _internal_mutable_header();
  // @@protoc_insertion_point(field_mutable:asr.v1.Response.header)
  return _msg;
}
inline void Response::set_allocated_header(::asr::v1::Response_Header* header) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete _impl_.header_;
  }
  if (header) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(header);
    if (message_arena != submessage_arena) {
      header = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, header, submessage_arena);
    }
    
  } else {
    
  }
  _impl_.header_ = header;
  // @@protoc_insertion_point(field_set_allocated:asr.v1.Response.header)
}

// .asr.v1.Response.Payload payload = 2;
inline bool Response::_internal_has_payload() const {
  return this != internal_default_instance() && _impl_.payload_ != nullptr;
}
inline bool Response::has_payload() const {
  return _internal_has_payload();
}
inline void Response::clear_payload() {
  if (GetArenaForAllocation() == nullptr && _impl_.payload_ != nullptr) {
    delete _impl_.payload_;
  }
  _impl_.payload_ = nullptr;
}
inline const ::asr::v1::Response_Payload& Response::_internal_payload() const {
  const ::asr::v1::Response_Payload* p = _impl_.payload_;
  return p != nullptr ? *p : reinterpret_cast<const ::asr::v1::Response_Payload&>(
      ::asr::v1::_Response_Payload_default_instance_);
}
inline const ::asr::v1::Response_Payload& Response::payload() const {
  // @@protoc_insertion_point(field_get:asr.v1.Response.payload)
  return _internal_payload();
}
inline void Response::unsafe_arena_set_allocated_payload(
    ::asr::v1::Response_Payload* payload) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.payload_);
  }
  _impl_.payload_ = payload;
  if (payload) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:asr.v1.Response.payload)
}
inline ::asr::v1::Response_Payload* Response::release_payload() {
  
  ::asr::v1::Response_Payload* temp = _impl_.payload_;
  _impl_.payload_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::asr::v1::Response_Payload* Response::unsafe_arena_release_payload() {
  // @@protoc_insertion_point(field_release:asr.v1.Response.payload)
  
  ::asr::v1::Response_Payload* temp = _impl_.payload_;
  _impl_.payload_ = nullptr;
  return temp;
}
inline ::asr::v1::Response_Payload* Response::_internal_mutable_payload() {
  
  if (_impl_.payload_ == nullptr) {
    auto* p = CreateMaybeMessage<::asr::v1::Response_Payload>(GetArenaForAllocation());
    _impl_.payload_ = p;
  }
  return _impl_.payload_;
}
inline ::asr::v1::Response_Payload* Response::mutable_payload() {
  ::asr::v1::Response_Payload* _msg = _internal_mutable_payload();
  // @@protoc_insertion_point(field_mutable:asr.v1.Response.payload)
  return _msg;
}
inline void Response::set_allocated_payload(::asr::v1::Response_Payload* payload) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete _impl_.payload_;
  }
  if (payload) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(payload);
    if (message_arena != submessage_arena) {
      payload = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, payload, submessage_arena);
    }
    
  } else {
    
  }
  _impl_.payload_ = payload;
  // @@protoc_insertion_point(field_set_allocated:asr.v1.Response.payload)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace v1
}  // namespace asr

PROTOBUF_NAMESPACE_OPEN

template <> struct is_proto_enum< ::asr::v1::Response_Status> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::asr::v1::Response_Status>() {
  return ::asr::v1::Response_Status_descriptor();
}
template <> struct is_proto_enum< ::asr::v1::Response_Type> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::asr::v1::Response_Type>() {
  return ::asr::v1::Response_Type_descriptor();
}

PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_grpc_2fasr_2eproto
