// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: grpc/asr.proto

#include "grpc/asr.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace asr {
namespace v1 {
PROTOBUF_CONSTEXPR Request_DecodeConfig::Request_DecodeConfig(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.req_id_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.nbest_)*/0
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct Request_DecodeConfigDefaultTypeInternal {
  PROTOBUF_CONSTEXPR Request_DecodeConfigDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~Request_DecodeConfigDefaultTypeInternal() {}
  union {
    Request_DecodeConfig _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 Request_DecodeConfigDefaultTypeInternal _Request_DecodeConfig_default_instance_;
PROTOBUF_CONSTEXPR Request::Request(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.payload_)*/{}
  , /*decltype(_impl_._cached_size_)*/{}
  , /*decltype(_impl_._oneof_case_)*/{}} {}
struct RequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR RequestDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~RequestDefaultTypeInternal() {}
  union {
    Request _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 RequestDefaultTypeInternal _Request_default_instance_;
PROTOBUF_CONSTEXPR OneBest::OneBest(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.wordpieces_)*/{}
  , /*decltype(_impl_.sentence_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct OneBestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR OneBestDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~OneBestDefaultTypeInternal() {}
  union {
    OneBest _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 OneBestDefaultTypeInternal _OneBest_default_instance_;
PROTOBUF_CONSTEXPR OnePiece::OnePiece(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.word_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.start_)*/0
  , /*decltype(_impl_.end_)*/0
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct OnePieceDefaultTypeInternal {
  PROTOBUF_CONSTEXPR OnePieceDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~OnePieceDefaultTypeInternal() {}
  union {
    OnePiece _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 OnePieceDefaultTypeInternal _OnePiece_default_instance_;
PROTOBUF_CONSTEXPR Response_Header::Response_Header(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.status_)*/0
  , /*decltype(_impl_.type_)*/0
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct Response_HeaderDefaultTypeInternal {
  PROTOBUF_CONSTEXPR Response_HeaderDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~Response_HeaderDefaultTypeInternal() {}
  union {
    Response_Header _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 Response_HeaderDefaultTypeInternal _Response_Header_default_instance_;
PROTOBUF_CONSTEXPR Response_Payload::Response_Payload(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.result_)*/{}
  , /*decltype(_impl_.text_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct Response_PayloadDefaultTypeInternal {
  PROTOBUF_CONSTEXPR Response_PayloadDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~Response_PayloadDefaultTypeInternal() {}
  union {
    Response_Payload _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 Response_PayloadDefaultTypeInternal _Response_Payload_default_instance_;
PROTOBUF_CONSTEXPR Response::Response(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.header_)*/nullptr
  , /*decltype(_impl_.payload_)*/nullptr
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct ResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ResponseDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~ResponseDefaultTypeInternal() {}
  union {
    Response _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ResponseDefaultTypeInternal _Response_default_instance_;
}  // namespace v1
}  // namespace asr
static ::_pb::Metadata file_level_metadata_grpc_2fasr_2eproto[7];
static const ::_pb::EnumDescriptor* file_level_enum_descriptors_grpc_2fasr_2eproto[2];
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_grpc_2fasr_2eproto = nullptr;

const uint32_t TableStruct_grpc_2fasr_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::asr::v1::Request_DecodeConfig, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::asr::v1::Request_DecodeConfig, _impl_.req_id_),
  PROTOBUF_FIELD_OFFSET(::asr::v1::Request_DecodeConfig, _impl_.nbest_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::asr::v1::Request, _internal_metadata_),
  ~0u,  // no _extensions_
  PROTOBUF_FIELD_OFFSET(::asr::v1::Request, _impl_._oneof_case_[0]),
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  ::_pbi::kInvalidFieldOffsetTag,
  ::_pbi::kInvalidFieldOffsetTag,
  PROTOBUF_FIELD_OFFSET(::asr::v1::Request, _impl_.payload_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::asr::v1::OneBest, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::asr::v1::OneBest, _impl_.sentence_),
  PROTOBUF_FIELD_OFFSET(::asr::v1::OneBest, _impl_.wordpieces_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::asr::v1::OnePiece, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::asr::v1::OnePiece, _impl_.word_),
  PROTOBUF_FIELD_OFFSET(::asr::v1::OnePiece, _impl_.start_),
  PROTOBUF_FIELD_OFFSET(::asr::v1::OnePiece, _impl_.end_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::asr::v1::Response_Header, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::asr::v1::Response_Header, _impl_.status_),
  PROTOBUF_FIELD_OFFSET(::asr::v1::Response_Header, _impl_.type_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::asr::v1::Response_Payload, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::asr::v1::Response_Payload, _impl_.result_),
  PROTOBUF_FIELD_OFFSET(::asr::v1::Response_Payload, _impl_.text_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::asr::v1::Response, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::asr::v1::Response, _impl_.header_),
  PROTOBUF_FIELD_OFFSET(::asr::v1::Response, _impl_.payload_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::asr::v1::Request_DecodeConfig)},
  { 8, -1, -1, sizeof(::asr::v1::Request)},
  { 17, -1, -1, sizeof(::asr::v1::OneBest)},
  { 25, -1, -1, sizeof(::asr::v1::OnePiece)},
  { 34, -1, -1, sizeof(::asr::v1::Response_Header)},
  { 42, -1, -1, sizeof(::asr::v1::Response_Payload)},
  { 50, -1, -1, sizeof(::asr::v1::Response)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::asr::v1::_Request_DecodeConfig_default_instance_._instance,
  &::asr::v1::_Request_default_instance_._instance,
  &::asr::v1::_OneBest_default_instance_._instance,
  &::asr::v1::_OnePiece_default_instance_._instance,
  &::asr::v1::_Response_Header_default_instance_._instance,
  &::asr::v1::_Response_Payload_default_instance_._instance,
  &::asr::v1::_Response_default_instance_._instance,
};

const char descriptor_table_protodef_grpc_2fasr_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\016grpc/asr.proto\022\006asr.v1\"\220\001\n\007Request\0225\n\r"
  "decode_config\030\001 \001(\0132\034.asr.v1.Request.Dec"
  "odeConfigH\000\022\024\n\naudio_data\030\002 \001(\014H\000\032-\n\014Dec"
  "odeConfig\022\016\n\006req_id\030\001 \001(\t\022\r\n\005nbest\030\002 \001(\005"
  "B\t\n\007payload\"A\n\007OneBest\022\020\n\010sentence\030\001 \001(\t"
  "\022$\n\nwordpieces\030\002 \003(\0132\020.asr.v1.OnePiece\"4"
  "\n\010OnePiece\022\014\n\004word\030\001 \001(\t\022\r\n\005start\030\002 \001(\005\022"
  "\013\n\003end\030\003 \001(\005\"\363\002\n\010Response\022\'\n\006header\030\001 \001("
  "\0132\027.asr.v1.Response.Header\022)\n\007payload\030\002 "
  "\001(\0132\030.asr.v1.Response.Payload\032V\n\006Header\022"
  "\'\n\006status\030\001 \001(\0162\027.asr.v1.Response.Status"
  "\022#\n\004type\030\002 \001(\0162\025.asr.v1.Response.Type\0328\n"
  "\007Payload\022\037\n\006result\030\001 \003(\0132\017.asr.v1.OneBes"
  "t\022\014\n\004text\030\002 \001(\t\"0\n\006Status\022\022\n\016UNKNOWN_STA"
  "TUS\020\000\022\006\n\002OK\020\001\022\n\n\006FAILED\020\002\"O\n\004Type\022\020\n\014UNK"
  "NOWN_TYPE\020\000\022\024\n\020SENTENCE_CHANGED\020\001\022\020\n\014SEN"
  "TENCE_END\020\002\022\r\n\tCOMPLETED\020\0032\224\001\n\003ASR\022G\n\034On"
  "eSentenceSpeechRecognition\022\017.asr.v1.Requ"
  "est\032\020.asr.v1.Response\"\000(\0010\001\022D\n\031RealTimeS"
  "peechRecognition\022\017.asr.v1.Request\032\020.asr."
  "v1.Response\"\000(\0010\001B\037\n\035com.mthreads.ai.pro"
  "tos.asr.v1b\006proto3"
  ;
static ::_pbi::once_flag descriptor_table_grpc_2fasr_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_grpc_2fasr_2eproto = {
    false, false, 858, descriptor_table_protodef_grpc_2fasr_2eproto,
    "grpc/asr.proto",
    &descriptor_table_grpc_2fasr_2eproto_once, nullptr, 0, 7,
    schemas, file_default_instances, TableStruct_grpc_2fasr_2eproto::offsets,
    file_level_metadata_grpc_2fasr_2eproto, file_level_enum_descriptors_grpc_2fasr_2eproto,
    file_level_service_descriptors_grpc_2fasr_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_grpc_2fasr_2eproto_getter() {
  return &descriptor_table_grpc_2fasr_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_grpc_2fasr_2eproto(&descriptor_table_grpc_2fasr_2eproto);
namespace asr {
namespace v1 {
const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* Response_Status_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_grpc_2fasr_2eproto);
  return file_level_enum_descriptors_grpc_2fasr_2eproto[0];
}
bool Response_Status_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
      return true;
    default:
      return false;
  }
}

#if (__cplusplus < 201703) && (!defined(_MSC_VER) || (_MSC_VER >= 1900 && _MSC_VER < 1912))
constexpr Response_Status Response::UNKNOWN_STATUS;
constexpr Response_Status Response::OK;
constexpr Response_Status Response::FAILED;
constexpr Response_Status Response::Status_MIN;
constexpr Response_Status Response::Status_MAX;
constexpr int Response::Status_ARRAYSIZE;
#endif  // (__cplusplus < 201703) && (!defined(_MSC_VER) || (_MSC_VER >= 1900 && _MSC_VER < 1912))
const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* Response_Type_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_grpc_2fasr_2eproto);
  return file_level_enum_descriptors_grpc_2fasr_2eproto[1];
}
bool Response_Type_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
      return true;
    default:
      return false;
  }
}

#if (__cplusplus < 201703) && (!defined(_MSC_VER) || (_MSC_VER >= 1900 && _MSC_VER < 1912))
constexpr Response_Type Response::UNKNOWN_TYPE;
constexpr Response_Type Response::SENTENCE_CHANGED;
constexpr Response_Type Response::SENTENCE_END;
constexpr Response_Type Response::COMPLETED;
constexpr Response_Type Response::Type_MIN;
constexpr Response_Type Response::Type_MAX;
constexpr int Response::Type_ARRAYSIZE;
#endif  // (__cplusplus < 201703) && (!defined(_MSC_VER) || (_MSC_VER >= 1900 && _MSC_VER < 1912))

// ===================================================================

class Request_DecodeConfig::_Internal {
 public:
};

Request_DecodeConfig::Request_DecodeConfig(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:asr.v1.Request.DecodeConfig)
}
Request_DecodeConfig::Request_DecodeConfig(const Request_DecodeConfig& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  Request_DecodeConfig* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.req_id_){}
    , decltype(_impl_.nbest_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.req_id_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.req_id_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_req_id().empty()) {
    _this->_impl_.req_id_.Set(from._internal_req_id(), 
      _this->GetArenaForAllocation());
  }
  _this->_impl_.nbest_ = from._impl_.nbest_;
  // @@protoc_insertion_point(copy_constructor:asr.v1.Request.DecodeConfig)
}

inline void Request_DecodeConfig::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.req_id_){}
    , decltype(_impl_.nbest_){0}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.req_id_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.req_id_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

Request_DecodeConfig::~Request_DecodeConfig() {
  // @@protoc_insertion_point(destructor:asr.v1.Request.DecodeConfig)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void Request_DecodeConfig::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.req_id_.Destroy();
}

void Request_DecodeConfig::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void Request_DecodeConfig::Clear() {
// @@protoc_insertion_point(message_clear_start:asr.v1.Request.DecodeConfig)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.req_id_.ClearToEmpty();
  _impl_.nbest_ = 0;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* Request_DecodeConfig::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // string req_id = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          auto str = _internal_mutable_req_id();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "asr.v1.Request.DecodeConfig.req_id"));
        } else
          goto handle_unusual;
        continue;
      // int32 nbest = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          _impl_.nbest_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* Request_DecodeConfig::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:asr.v1.Request.DecodeConfig)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // string req_id = 1;
  if (!this->_internal_req_id().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_req_id().data(), static_cast<int>(this->_internal_req_id().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "asr.v1.Request.DecodeConfig.req_id");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_req_id(), target);
  }

  // int32 nbest = 2;
  if (this->_internal_nbest() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(2, this->_internal_nbest(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:asr.v1.Request.DecodeConfig)
  return target;
}

size_t Request_DecodeConfig::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:asr.v1.Request.DecodeConfig)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string req_id = 1;
  if (!this->_internal_req_id().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_req_id());
  }

  // int32 nbest = 2;
  if (this->_internal_nbest() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_nbest());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData Request_DecodeConfig::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    Request_DecodeConfig::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*Request_DecodeConfig::GetClassData() const { return &_class_data_; }


void Request_DecodeConfig::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<Request_DecodeConfig*>(&to_msg);
  auto& from = static_cast<const Request_DecodeConfig&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:asr.v1.Request.DecodeConfig)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_req_id().empty()) {
    _this->_internal_set_req_id(from._internal_req_id());
  }
  if (from._internal_nbest() != 0) {
    _this->_internal_set_nbest(from._internal_nbest());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void Request_DecodeConfig::CopyFrom(const Request_DecodeConfig& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:asr.v1.Request.DecodeConfig)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Request_DecodeConfig::IsInitialized() const {
  return true;
}

void Request_DecodeConfig::InternalSwap(Request_DecodeConfig* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.req_id_, lhs_arena,
      &other->_impl_.req_id_, rhs_arena
  );
  swap(_impl_.nbest_, other->_impl_.nbest_);
}

::PROTOBUF_NAMESPACE_ID::Metadata Request_DecodeConfig::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_grpc_2fasr_2eproto_getter, &descriptor_table_grpc_2fasr_2eproto_once,
      file_level_metadata_grpc_2fasr_2eproto[0]);
}

// ===================================================================

class Request::_Internal {
 public:
  static const ::asr::v1::Request_DecodeConfig& decode_config(const Request* msg);
};

const ::asr::v1::Request_DecodeConfig&
Request::_Internal::decode_config(const Request* msg) {
  return *msg->_impl_.payload_.decode_config_;
}
void Request::set_allocated_decode_config(::asr::v1::Request_DecodeConfig* decode_config) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  clear_payload();
  if (decode_config) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(decode_config);
    if (message_arena != submessage_arena) {
      decode_config = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, decode_config, submessage_arena);
    }
    set_has_decode_config();
    _impl_.payload_.decode_config_ = decode_config;
  }
  // @@protoc_insertion_point(field_set_allocated:asr.v1.Request.decode_config)
}
Request::Request(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:asr.v1.Request)
}
Request::Request(const Request& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  Request* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.payload_){}
    , /*decltype(_impl_._cached_size_)*/{}
    , /*decltype(_impl_._oneof_case_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  clear_has_payload();
  switch (from.payload_case()) {
    case kDecodeConfig: {
      _this->_internal_mutable_decode_config()->::asr::v1::Request_DecodeConfig::MergeFrom(
          from._internal_decode_config());
      break;
    }
    case kAudioData: {
      _this->_internal_set_audio_data(from._internal_audio_data());
      break;
    }
    case PAYLOAD_NOT_SET: {
      break;
    }
  }
  // @@protoc_insertion_point(copy_constructor:asr.v1.Request)
}

inline void Request::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.payload_){}
    , /*decltype(_impl_._cached_size_)*/{}
    , /*decltype(_impl_._oneof_case_)*/{}
  };
  clear_has_payload();
}

Request::~Request() {
  // @@protoc_insertion_point(destructor:asr.v1.Request)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void Request::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  if (has_payload()) {
    clear_payload();
  }
}

void Request::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void Request::clear_payload() {
// @@protoc_insertion_point(one_of_clear_start:asr.v1.Request)
  switch (payload_case()) {
    case kDecodeConfig: {
      if (GetArenaForAllocation() == nullptr) {
        delete _impl_.payload_.decode_config_;
      }
      break;
    }
    case kAudioData: {
      _impl_.payload_.audio_data_.Destroy();
      break;
    }
    case PAYLOAD_NOT_SET: {
      break;
    }
  }
  _impl_._oneof_case_[0] = PAYLOAD_NOT_SET;
}


void Request::Clear() {
// @@protoc_insertion_point(message_clear_start:asr.v1.Request)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  clear_payload();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* Request::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // .asr.v1.Request.DecodeConfig decode_config = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          ptr = ctx->ParseMessage(_internal_mutable_decode_config(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // bytes audio_data = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          auto str = _internal_mutable_audio_data();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* Request::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:asr.v1.Request)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // .asr.v1.Request.DecodeConfig decode_config = 1;
  if (_internal_has_decode_config()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(1, _Internal::decode_config(this),
        _Internal::decode_config(this).GetCachedSize(), target, stream);
  }

  // bytes audio_data = 2;
  if (_internal_has_audio_data()) {
    target = stream->WriteBytesMaybeAliased(
        2, this->_internal_audio_data(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:asr.v1.Request)
  return target;
}

size_t Request::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:asr.v1.Request)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  switch (payload_case()) {
    // .asr.v1.Request.DecodeConfig decode_config = 1;
    case kDecodeConfig: {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *_impl_.payload_.decode_config_);
      break;
    }
    // bytes audio_data = 2;
    case kAudioData: {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::BytesSize(
          this->_internal_audio_data());
      break;
    }
    case PAYLOAD_NOT_SET: {
      break;
    }
  }
  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData Request::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    Request::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*Request::GetClassData() const { return &_class_data_; }


void Request::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<Request*>(&to_msg);
  auto& from = static_cast<const Request&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:asr.v1.Request)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  switch (from.payload_case()) {
    case kDecodeConfig: {
      _this->_internal_mutable_decode_config()->::asr::v1::Request_DecodeConfig::MergeFrom(
          from._internal_decode_config());
      break;
    }
    case kAudioData: {
      _this->_internal_set_audio_data(from._internal_audio_data());
      break;
    }
    case PAYLOAD_NOT_SET: {
      break;
    }
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void Request::CopyFrom(const Request& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:asr.v1.Request)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Request::IsInitialized() const {
  return true;
}

void Request::InternalSwap(Request* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_.payload_, other->_impl_.payload_);
  swap(_impl_._oneof_case_[0], other->_impl_._oneof_case_[0]);
}

::PROTOBUF_NAMESPACE_ID::Metadata Request::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_grpc_2fasr_2eproto_getter, &descriptor_table_grpc_2fasr_2eproto_once,
      file_level_metadata_grpc_2fasr_2eproto[1]);
}

// ===================================================================

class OneBest::_Internal {
 public:
};

OneBest::OneBest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:asr.v1.OneBest)
}
OneBest::OneBest(const OneBest& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  OneBest* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.wordpieces_){from._impl_.wordpieces_}
    , decltype(_impl_.sentence_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.sentence_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.sentence_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_sentence().empty()) {
    _this->_impl_.sentence_.Set(from._internal_sentence(), 
      _this->GetArenaForAllocation());
  }
  // @@protoc_insertion_point(copy_constructor:asr.v1.OneBest)
}

inline void OneBest::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.wordpieces_){arena}
    , decltype(_impl_.sentence_){}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.sentence_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.sentence_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

OneBest::~OneBest() {
  // @@protoc_insertion_point(destructor:asr.v1.OneBest)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void OneBest::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.wordpieces_.~RepeatedPtrField();
  _impl_.sentence_.Destroy();
}

void OneBest::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void OneBest::Clear() {
// @@protoc_insertion_point(message_clear_start:asr.v1.OneBest)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.wordpieces_.Clear();
  _impl_.sentence_.ClearToEmpty();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* OneBest::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // string sentence = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          auto str = _internal_mutable_sentence();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "asr.v1.OneBest.sentence"));
        } else
          goto handle_unusual;
        continue;
      // repeated .asr.v1.OnePiece wordpieces = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_wordpieces(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<18>(ptr));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* OneBest::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:asr.v1.OneBest)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // string sentence = 1;
  if (!this->_internal_sentence().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_sentence().data(), static_cast<int>(this->_internal_sentence().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "asr.v1.OneBest.sentence");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_sentence(), target);
  }

  // repeated .asr.v1.OnePiece wordpieces = 2;
  for (unsigned i = 0,
      n = static_cast<unsigned>(this->_internal_wordpieces_size()); i < n; i++) {
    const auto& repfield = this->_internal_wordpieces(i);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
        InternalWriteMessage(2, repfield, repfield.GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:asr.v1.OneBest)
  return target;
}

size_t OneBest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:asr.v1.OneBest)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated .asr.v1.OnePiece wordpieces = 2;
  total_size += 1UL * this->_internal_wordpieces_size();
  for (const auto& msg : this->_impl_.wordpieces_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  // string sentence = 1;
  if (!this->_internal_sentence().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_sentence());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData OneBest::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    OneBest::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*OneBest::GetClassData() const { return &_class_data_; }


void OneBest::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<OneBest*>(&to_msg);
  auto& from = static_cast<const OneBest&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:asr.v1.OneBest)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_impl_.wordpieces_.MergeFrom(from._impl_.wordpieces_);
  if (!from._internal_sentence().empty()) {
    _this->_internal_set_sentence(from._internal_sentence());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void OneBest::CopyFrom(const OneBest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:asr.v1.OneBest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool OneBest::IsInitialized() const {
  return true;
}

void OneBest::InternalSwap(OneBest* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.wordpieces_.InternalSwap(&other->_impl_.wordpieces_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.sentence_, lhs_arena,
      &other->_impl_.sentence_, rhs_arena
  );
}

::PROTOBUF_NAMESPACE_ID::Metadata OneBest::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_grpc_2fasr_2eproto_getter, &descriptor_table_grpc_2fasr_2eproto_once,
      file_level_metadata_grpc_2fasr_2eproto[2]);
}

// ===================================================================

class OnePiece::_Internal {
 public:
};

OnePiece::OnePiece(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:asr.v1.OnePiece)
}
OnePiece::OnePiece(const OnePiece& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  OnePiece* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.word_){}
    , decltype(_impl_.start_){}
    , decltype(_impl_.end_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.word_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.word_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_word().empty()) {
    _this->_impl_.word_.Set(from._internal_word(), 
      _this->GetArenaForAllocation());
  }
  ::memcpy(&_impl_.start_, &from._impl_.start_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.end_) -
    reinterpret_cast<char*>(&_impl_.start_)) + sizeof(_impl_.end_));
  // @@protoc_insertion_point(copy_constructor:asr.v1.OnePiece)
}

inline void OnePiece::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.word_){}
    , decltype(_impl_.start_){0}
    , decltype(_impl_.end_){0}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.word_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.word_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

OnePiece::~OnePiece() {
  // @@protoc_insertion_point(destructor:asr.v1.OnePiece)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void OnePiece::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.word_.Destroy();
}

void OnePiece::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void OnePiece::Clear() {
// @@protoc_insertion_point(message_clear_start:asr.v1.OnePiece)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.word_.ClearToEmpty();
  ::memset(&_impl_.start_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.end_) -
      reinterpret_cast<char*>(&_impl_.start_)) + sizeof(_impl_.end_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* OnePiece::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // string word = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          auto str = _internal_mutable_word();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "asr.v1.OnePiece.word"));
        } else
          goto handle_unusual;
        continue;
      // int32 start = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          _impl_.start_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int32 end = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 24)) {
          _impl_.end_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* OnePiece::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:asr.v1.OnePiece)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // string word = 1;
  if (!this->_internal_word().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_word().data(), static_cast<int>(this->_internal_word().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "asr.v1.OnePiece.word");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_word(), target);
  }

  // int32 start = 2;
  if (this->_internal_start() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(2, this->_internal_start(), target);
  }

  // int32 end = 3;
  if (this->_internal_end() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(3, this->_internal_end(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:asr.v1.OnePiece)
  return target;
}

size_t OnePiece::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:asr.v1.OnePiece)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string word = 1;
  if (!this->_internal_word().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_word());
  }

  // int32 start = 2;
  if (this->_internal_start() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_start());
  }

  // int32 end = 3;
  if (this->_internal_end() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_end());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData OnePiece::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    OnePiece::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*OnePiece::GetClassData() const { return &_class_data_; }


void OnePiece::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<OnePiece*>(&to_msg);
  auto& from = static_cast<const OnePiece&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:asr.v1.OnePiece)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_word().empty()) {
    _this->_internal_set_word(from._internal_word());
  }
  if (from._internal_start() != 0) {
    _this->_internal_set_start(from._internal_start());
  }
  if (from._internal_end() != 0) {
    _this->_internal_set_end(from._internal_end());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void OnePiece::CopyFrom(const OnePiece& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:asr.v1.OnePiece)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool OnePiece::IsInitialized() const {
  return true;
}

void OnePiece::InternalSwap(OnePiece* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.word_, lhs_arena,
      &other->_impl_.word_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(OnePiece, _impl_.end_)
      + sizeof(OnePiece::_impl_.end_)
      - PROTOBUF_FIELD_OFFSET(OnePiece, _impl_.start_)>(
          reinterpret_cast<char*>(&_impl_.start_),
          reinterpret_cast<char*>(&other->_impl_.start_));
}

::PROTOBUF_NAMESPACE_ID::Metadata OnePiece::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_grpc_2fasr_2eproto_getter, &descriptor_table_grpc_2fasr_2eproto_once,
      file_level_metadata_grpc_2fasr_2eproto[3]);
}

// ===================================================================

class Response_Header::_Internal {
 public:
};

Response_Header::Response_Header(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:asr.v1.Response.Header)
}
Response_Header::Response_Header(const Response_Header& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  Response_Header* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.status_){}
    , decltype(_impl_.type_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::memcpy(&_impl_.status_, &from._impl_.status_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.type_) -
    reinterpret_cast<char*>(&_impl_.status_)) + sizeof(_impl_.type_));
  // @@protoc_insertion_point(copy_constructor:asr.v1.Response.Header)
}

inline void Response_Header::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.status_){0}
    , decltype(_impl_.type_){0}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

Response_Header::~Response_Header() {
  // @@protoc_insertion_point(destructor:asr.v1.Response.Header)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void Response_Header::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void Response_Header::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void Response_Header::Clear() {
// @@protoc_insertion_point(message_clear_start:asr.v1.Response.Header)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&_impl_.status_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.type_) -
      reinterpret_cast<char*>(&_impl_.status_)) + sizeof(_impl_.type_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* Response_Header::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // .asr.v1.Response.Status status = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          uint64_t val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
          _internal_set_status(static_cast<::asr::v1::Response_Status>(val));
        } else
          goto handle_unusual;
        continue;
      // .asr.v1.Response.Type type = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          uint64_t val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
          _internal_set_type(static_cast<::asr::v1::Response_Type>(val));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* Response_Header::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:asr.v1.Response.Header)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // .asr.v1.Response.Status status = 1;
  if (this->_internal_status() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
      1, this->_internal_status(), target);
  }

  // .asr.v1.Response.Type type = 2;
  if (this->_internal_type() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
      2, this->_internal_type(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:asr.v1.Response.Header)
  return target;
}

size_t Response_Header::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:asr.v1.Response.Header)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // .asr.v1.Response.Status status = 1;
  if (this->_internal_status() != 0) {
    total_size += 1 +
      ::_pbi::WireFormatLite::EnumSize(this->_internal_status());
  }

  // .asr.v1.Response.Type type = 2;
  if (this->_internal_type() != 0) {
    total_size += 1 +
      ::_pbi::WireFormatLite::EnumSize(this->_internal_type());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData Response_Header::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    Response_Header::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*Response_Header::GetClassData() const { return &_class_data_; }


void Response_Header::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<Response_Header*>(&to_msg);
  auto& from = static_cast<const Response_Header&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:asr.v1.Response.Header)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_status() != 0) {
    _this->_internal_set_status(from._internal_status());
  }
  if (from._internal_type() != 0) {
    _this->_internal_set_type(from._internal_type());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void Response_Header::CopyFrom(const Response_Header& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:asr.v1.Response.Header)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Response_Header::IsInitialized() const {
  return true;
}

void Response_Header::InternalSwap(Response_Header* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(Response_Header, _impl_.type_)
      + sizeof(Response_Header::_impl_.type_)
      - PROTOBUF_FIELD_OFFSET(Response_Header, _impl_.status_)>(
          reinterpret_cast<char*>(&_impl_.status_),
          reinterpret_cast<char*>(&other->_impl_.status_));
}

::PROTOBUF_NAMESPACE_ID::Metadata Response_Header::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_grpc_2fasr_2eproto_getter, &descriptor_table_grpc_2fasr_2eproto_once,
      file_level_metadata_grpc_2fasr_2eproto[4]);
}

// ===================================================================

class Response_Payload::_Internal {
 public:
};

Response_Payload::Response_Payload(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:asr.v1.Response.Payload)
}
Response_Payload::Response_Payload(const Response_Payload& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  Response_Payload* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.result_){from._impl_.result_}
    , decltype(_impl_.text_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.text_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.text_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_text().empty()) {
    _this->_impl_.text_.Set(from._internal_text(), 
      _this->GetArenaForAllocation());
  }
  // @@protoc_insertion_point(copy_constructor:asr.v1.Response.Payload)
}

inline void Response_Payload::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.result_){arena}
    , decltype(_impl_.text_){}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.text_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.text_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

Response_Payload::~Response_Payload() {
  // @@protoc_insertion_point(destructor:asr.v1.Response.Payload)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void Response_Payload::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.result_.~RepeatedPtrField();
  _impl_.text_.Destroy();
}

void Response_Payload::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void Response_Payload::Clear() {
// @@protoc_insertion_point(message_clear_start:asr.v1.Response.Payload)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.result_.Clear();
  _impl_.text_.ClearToEmpty();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* Response_Payload::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // repeated .asr.v1.OneBest result = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_result(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<10>(ptr));
        } else
          goto handle_unusual;
        continue;
      // string text = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          auto str = _internal_mutable_text();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "asr.v1.Response.Payload.text"));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* Response_Payload::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:asr.v1.Response.Payload)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated .asr.v1.OneBest result = 1;
  for (unsigned i = 0,
      n = static_cast<unsigned>(this->_internal_result_size()); i < n; i++) {
    const auto& repfield = this->_internal_result(i);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
        InternalWriteMessage(1, repfield, repfield.GetCachedSize(), target, stream);
  }

  // string text = 2;
  if (!this->_internal_text().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_text().data(), static_cast<int>(this->_internal_text().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "asr.v1.Response.Payload.text");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_text(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:asr.v1.Response.Payload)
  return target;
}

size_t Response_Payload::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:asr.v1.Response.Payload)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated .asr.v1.OneBest result = 1;
  total_size += 1UL * this->_internal_result_size();
  for (const auto& msg : this->_impl_.result_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  // string text = 2;
  if (!this->_internal_text().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_text());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData Response_Payload::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    Response_Payload::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*Response_Payload::GetClassData() const { return &_class_data_; }


void Response_Payload::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<Response_Payload*>(&to_msg);
  auto& from = static_cast<const Response_Payload&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:asr.v1.Response.Payload)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_impl_.result_.MergeFrom(from._impl_.result_);
  if (!from._internal_text().empty()) {
    _this->_internal_set_text(from._internal_text());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void Response_Payload::CopyFrom(const Response_Payload& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:asr.v1.Response.Payload)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Response_Payload::IsInitialized() const {
  return true;
}

void Response_Payload::InternalSwap(Response_Payload* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.result_.InternalSwap(&other->_impl_.result_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.text_, lhs_arena,
      &other->_impl_.text_, rhs_arena
  );
}

::PROTOBUF_NAMESPACE_ID::Metadata Response_Payload::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_grpc_2fasr_2eproto_getter, &descriptor_table_grpc_2fasr_2eproto_once,
      file_level_metadata_grpc_2fasr_2eproto[5]);
}

// ===================================================================

class Response::_Internal {
 public:
  static const ::asr::v1::Response_Header& header(const Response* msg);
  static const ::asr::v1::Response_Payload& payload(const Response* msg);
};

const ::asr::v1::Response_Header&
Response::_Internal::header(const Response* msg) {
  return *msg->_impl_.header_;
}
const ::asr::v1::Response_Payload&
Response::_Internal::payload(const Response* msg) {
  return *msg->_impl_.payload_;
}
Response::Response(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:asr.v1.Response)
}
Response::Response(const Response& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  Response* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.header_){nullptr}
    , decltype(_impl_.payload_){nullptr}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  if (from._internal_has_header()) {
    _this->_impl_.header_ = new ::asr::v1::Response_Header(*from._impl_.header_);
  }
  if (from._internal_has_payload()) {
    _this->_impl_.payload_ = new ::asr::v1::Response_Payload(*from._impl_.payload_);
  }
  // @@protoc_insertion_point(copy_constructor:asr.v1.Response)
}

inline void Response::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.header_){nullptr}
    , decltype(_impl_.payload_){nullptr}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

Response::~Response() {
  // @@protoc_insertion_point(destructor:asr.v1.Response)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void Response::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  if (this != internal_default_instance()) delete _impl_.header_;
  if (this != internal_default_instance()) delete _impl_.payload_;
}

void Response::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void Response::Clear() {
// @@protoc_insertion_point(message_clear_start:asr.v1.Response)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  if (GetArenaForAllocation() == nullptr && _impl_.header_ != nullptr) {
    delete _impl_.header_;
  }
  _impl_.header_ = nullptr;
  if (GetArenaForAllocation() == nullptr && _impl_.payload_ != nullptr) {
    delete _impl_.payload_;
  }
  _impl_.payload_ = nullptr;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* Response::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // .asr.v1.Response.Header header = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          ptr = ctx->ParseMessage(_internal_mutable_header(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .asr.v1.Response.Payload payload = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          ptr = ctx->ParseMessage(_internal_mutable_payload(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* Response::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:asr.v1.Response)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // .asr.v1.Response.Header header = 1;
  if (this->_internal_has_header()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(1, _Internal::header(this),
        _Internal::header(this).GetCachedSize(), target, stream);
  }

  // .asr.v1.Response.Payload payload = 2;
  if (this->_internal_has_payload()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(2, _Internal::payload(this),
        _Internal::payload(this).GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:asr.v1.Response)
  return target;
}

size_t Response::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:asr.v1.Response)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // .asr.v1.Response.Header header = 1;
  if (this->_internal_has_header()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_impl_.header_);
  }

  // .asr.v1.Response.Payload payload = 2;
  if (this->_internal_has_payload()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_impl_.payload_);
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData Response::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    Response::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*Response::GetClassData() const { return &_class_data_; }


void Response::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<Response*>(&to_msg);
  auto& from = static_cast<const Response&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:asr.v1.Response)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_has_header()) {
    _this->_internal_mutable_header()->::asr::v1::Response_Header::MergeFrom(
        from._internal_header());
  }
  if (from._internal_has_payload()) {
    _this->_internal_mutable_payload()->::asr::v1::Response_Payload::MergeFrom(
        from._internal_payload());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void Response::CopyFrom(const Response& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:asr.v1.Response)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Response::IsInitialized() const {
  return true;
}

void Response::InternalSwap(Response* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(Response, _impl_.payload_)
      + sizeof(Response::_impl_.payload_)
      - PROTOBUF_FIELD_OFFSET(Response, _impl_.header_)>(
          reinterpret_cast<char*>(&_impl_.header_),
          reinterpret_cast<char*>(&other->_impl_.header_));
}

::PROTOBUF_NAMESPACE_ID::Metadata Response::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_grpc_2fasr_2eproto_getter, &descriptor_table_grpc_2fasr_2eproto_once,
      file_level_metadata_grpc_2fasr_2eproto[6]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace v1
}  // namespace asr
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::asr::v1::Request_DecodeConfig*
Arena::CreateMaybeMessage< ::asr::v1::Request_DecodeConfig >(Arena* arena) {
  return Arena::CreateMessageInternal< ::asr::v1::Request_DecodeConfig >(arena);
}
template<> PROTOBUF_NOINLINE ::asr::v1::Request*
Arena::CreateMaybeMessage< ::asr::v1::Request >(Arena* arena) {
  return Arena::CreateMessageInternal< ::asr::v1::Request >(arena);
}
template<> PROTOBUF_NOINLINE ::asr::v1::OneBest*
Arena::CreateMaybeMessage< ::asr::v1::OneBest >(Arena* arena) {
  return Arena::CreateMessageInternal< ::asr::v1::OneBest >(arena);
}
template<> PROTOBUF_NOINLINE ::asr::v1::OnePiece*
Arena::CreateMaybeMessage< ::asr::v1::OnePiece >(Arena* arena) {
  return Arena::CreateMessageInternal< ::asr::v1::OnePiece >(arena);
}
template<> PROTOBUF_NOINLINE ::asr::v1::Response_Header*
Arena::CreateMaybeMessage< ::asr::v1::Response_Header >(Arena* arena) {
  return Arena::CreateMessageInternal< ::asr::v1::Response_Header >(arena);
}
template<> PROTOBUF_NOINLINE ::asr::v1::Response_Payload*
Arena::CreateMaybeMessage< ::asr::v1::Response_Payload >(Arena* arena) {
  return Arena::CreateMessageInternal< ::asr::v1::Response_Payload >(arena);
}
template<> PROTOBUF_NOINLINE ::asr::v1::Response*
Arena::CreateMaybeMessage< ::asr::v1::Response >(Arena* arena) {
  return Arena::CreateMessageInternal< ::asr::v1::Response >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
